import { useEffect, useState } from "react";
import { http } from "../../../api/http";
import { readApiError } from "../sales/ui";
import { printCutLabels, type StockCut } from "../components/printing";
export function CutStock({companyId,branchId}:{companyId:string;branchId:string}){
 const [q,setQ]=useState(""),[page,setPage]=useState(1),[rows,setRows]=useState<StockCut[]>([]),[total,setTotal]=useState(0),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 useEffect(()=>setPage(1),[q,companyId,branchId]);
 useEffect(()=>{const c=new AbortController();const t=setTimeout(()=>{setLoading(true);setError("");setSelected([]);http.get<{items:StockCut[];total:number}>("/companies/"+companyId+"/operations-query/cuts",{params:{branchId:branchId||undefined,q:q||undefined,page,pageSize:25},signal:c.signal}).then(r=>{if(!c.signal.aborted){setRows(r.data.items);setTotal(r.data.total);}}).catch(e=>{if(!c.signal.aborted){setRows([]);setError(readApiError(e));}}).finally(()=>{if(!c.signal.aborted)setLoading(false);});},200);return()=>{clearTimeout(t);c.abort();};},[companyId,branchId,q,page,revision]);
 return <section className="co-workspace"><header className="co-heading"><div><span className="co-eyebrow">Butchery / Inventory</span><h1>Stock by cut</h1><p>Remaining produced lots from posted butchery batches.</p></div><div className="co-actions"><button disabled={loading} onClick={()=>setRevision(r=>r+1)}>Refresh</button><button className="co-primary" disabled={loading||!selected.length} onClick={()=>printCutLabels(rows.filter(r=>selected.includes(r.lotId)))}>Print selected labels ({selected.length})</button></div></header>{error&&<p role="alert" className="co-notice">{error}</p>}<section className="co-card"><div className="co-toolbar"><input aria-label="Search produced cuts" placeholder="Search cut, batch or lot..." value={q} onChange={e=>setQ(e.target.value)}/><span>{total} lots</span></div><div className="co-table-wrap"><table className="co-table"><thead><tr><th><input aria-label="Select all labels on this page" type="checkbox" checked={rows.length>0&&selected.length===rows.length} onChange={e=>setSelected(e.target.checked?rows.map(r=>r.lotId):[])}/></th><th>Cut</th><th>Produced lot</th><th>Batch</th><th>Remaining kg</th><th>Expiry</th></tr></thead><tbody>{rows.map(r=><tr key={r.lotId}><td><input aria-label={"Select label "+r.lot} type="checkbox" checked={selected.includes(r.lotId)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,r.lotId]:ids.filter(id=>id!==r.lotId))}/></td><td>{r.cut}</td><td>{r.lot??"Not recorded"}</td><td>{r.batchNo}</td><td>{r.remainingQty.toFixed(2)}</td><td>{r.expiryDate??"Not recorded"}</td></tr>)}</tbody></table></div>{loading?<p className="co-empty" role="status">Loading stock...</p>:!rows.length?<p className="co-empty">No matching produced lots.</p>:null}<footer className="co-toolbar"><span>Page {page} of {Math.max(1,Math.ceil(total/25))}</span><div className="co-actions"><button disabled={loading||page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={loading||page*25>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></footer></section></section>;
}
