import { printDocument } from "../components/printing";
import { useUnsavedChanges } from "../components/useUnsavedChanges";
import { useDialogFocus } from "../components/useDialogFocus";
import { useEffect, useRef, useState } from "react";
import { http } from "../../../api/http";
import { useAuth } from "../../../auth/AuthProvider";
import { formatCurrency } from "../../../shared/currency/currencyFormat";
import { humanize } from "../sales/options";
import { readApiError, toDateTimeInput } from "../sales/ui";
import type { CateringEventDto } from "../api/cateringManagementApi";
type Kind="staffing-plans"|"equipment-plans"|"production-plans"|"dispatches"|"final-bills";
type Line=Record<string,string|number|null>;
type Document={id:string;planNo?:string;billNo?:string;dispatchNo?:string;status:string;lines:Line[];billDateUtc?:string;contractAmount?:number;guestCountAdjustmentAmount?:number;subtotalAmount?:number;taxAmount?:number;discountAmount?:number;depositPaidAmount?:number;paymentsReceivedAmount?:number;refundAmount?:number;grandTotalAmount?:number;balanceDueAmount?:number;notes?:string};
type Field={key:string;label:string;type?:"number"|"datetime-local"|"employee";options?:string[];required?:boolean;min?:number};
const roles=["eventManager","executiveChef","chef","cook","waiter","bartender","cashier","driver","cleaner","setupCrew","security","other"];
const equipment=["tables","chairs","chafingDishes","coffeeMachines","plates","glasses","cutlery","servingEquipment","tents","soundEquipment","vehicle","other"];
const configs:Record<Kind,{label:string;permission:string;fields:Field[];states:string[]}> = {
 "staffing-plans":{label:"Staffing",permission:"catering.staffing.manage",fields:[{key:"role",label:"Role",options:roles,required:true},{key:"employeeId",label:"Employee",type:"employee"},{key:"shiftStartUtc",label:"Shift start",type:"datetime-local",required:true},{key:"shiftEndUtc",label:"Shift end",type:"datetime-local",required:true}],states:["open","assigned","confirmed","inProgress","completed","cancelled"]},
 "equipment-plans":{label:"Equipment",permission:"catering.equipment.manage",fields:[{key:"equipmentType",label:"Equipment type",options:equipment,required:true},{key:"equipmentName",label:"Equipment name",required:true},{key:"requiredQuantity",label:"Required quantity",type:"number",required:true,min:0.01},{key:"allocatedQuantity",label:"Allocated quantity",type:"number",min:0},{key:"neededFromUtc",label:"Needed from",type:"datetime-local",required:true},{key:"neededUntilUtc",label:"Needed until",type:"datetime-local",required:true},{key:"responsibleEmployeeId",label:"Responsible employee",type:"employee"}],states:["short","allocated","packed","dispatched","returned","cancelled"]},
 "production-plans":{label:"Production",permission:"catering.production.manage",fields:[{key:"responsibleEmployeeId",label:"Responsible employee",type:"employee"},{key:"productionDueAtUtc",label:"Production due",type:"datetime-local",required:true}],states:["planned","inProgress","completed","cancelled"]},
 "dispatches":{label:"Dispatch",permission:"catering.dispatch.manage",fields:[{key:"lineType",label:"Line type",options:["food","equipment","supply","other"],required:true},{key:"description",label:"Description",required:true},{key:"quantity",label:"Quantity",type:"number",required:true,min:0.01},{key:"uomCode",label:"Unit",required:true}],states:["planned","loaded","dispatched","delivered","returned","cancelled"]},
 "final-bills":{label:"Invoicing",permission:"catering.billing.manage",fields:[{key:"lineType",label:"Charge type",options:["additionalFood","additionalLabor","additionalEquipment","transportation","damageLoss","otherCharge","discount","tax"],required:true},{key:"description",label:"Description",required:true},{key:"quantity",label:"Quantity",type:"number",required:true,min:0.01},{key:"unitPrice",label:"Unit price",type:"number",required:true,min:0}],states:[]}
};
export function EventDocuments({event,mode}:{event:CateringEventDto|null;mode:"event"|"kitchen"|"finance"}){
 const {hasPermission}=useAuth();
 const kinds:Kind[]=mode==="event"?["staffing-plans","equipment-plans","dispatches"]:mode==="kitchen"?["production-plans"]:["final-bills"];
 const [kind,setKind]=useState<Kind>(kinds[0]),[docs,setDocs]=useState<Document[]>([]),[selected,setSelected]=useState(""),[revision,setRevision]=useState(0);
 const [error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const lock=useRef(false);
 const [employeeSearch,setEmployeeSearch]=useState(""),[employeeError,setEmployeeError]=useState("");
 const [employees,setEmployees]=useState<{id:string;fullName?:string;displayName?:string;employeeNo?:string}[]>([]);
 const [draft,setDraft]=useState<Line[]|null>(null),[editLine,setEditLine]=useState<Line|null>(null),[notes,setNotes]=useState(""),[activate,setActivate]=useState(true);
 const [extra,setExtra]=useState<Line>({}),[confirm,setConfirm]=useState<{action:string;label:string}|null>(null),[reason,setReason]=useState("");
 const guard=useUnsavedChanges(!!(draft||editLine));
 const closeDraft=()=>{if(guard.confirmDiscard()){setDraft(null);setEditLine(null);setConfirm(null);}};
 useDialogFocus(!!(draft||editLine||confirm),busy,closeDraft);
 const cfg=configs[kind],doc=docs.find(d=>d.id===selected)??null,canManage=hasPermission(cfg.permission);
 const path=event?"/companies/"+event.companyId+"/catering/events/"+event.id+"/"+kind:"";
 useEffect(()=>{const c=new AbortController();setDocs([]);setError("");setLoading(true);setDraft(null);setEditLine(null);setConfirm(null);
 if(!path){setLoading(false);return;}
 http.get<Document[]>(path,{signal:c.signal}).then(r=>{if(!c.signal.aborted){setDocs(r.data);setSelected(id=>r.data.some(d=>d.id===id)?id:r.data[0]?.id??"");}}).catch(e=>{if(!c.signal.aborted)setError(readApiError(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[path,revision]);
 useEffect(()=>{const c=new AbortController();setEmployees([]);setEmployeeError("");if(event&&mode!=="finance")http.get<{id:string;fullName?:string;displayName?:string;employeeNo?:string}[]|{items:{id:string;fullName?:string;displayName?:string;employeeNo?:string}[]}>("/companies/"+event.companyId+"/hr/employees",{params:{branchId:event.branchId,pageSize:50,search:employeeSearch},signal:c.signal}).then(r=>{if(!c.signal.aborted)setEmployees(Array.isArray(r.data)?r.data:r.data.items??[]);}).catch(()=>{if(!c.signal.aborted)setEmployeeError("Employee lookup is unavailable. Check HR viewing permission or try again.");});return()=>c.abort();},[event?.companyId,event?.branchId,mode,employeeSearch]);
 async function mutate(call:()=>Promise<unknown>,success:string){if(lock.current)return;lock.current=true;setBusy(true);setError("");setMessage("");try{const result=await call(); if(result && typeof result==="object" && "data" in result){const data=result.data as {id?:string}; if(data?.id)setSelected(data.id);}guard.markSaved();setDraft(null);setEditLine(null);setConfirm(null);setRevision(v=>v+1);setMessage(success);}catch(e){setError(readApiError(e));}finally{lock.current=false;setBusy(false);}}
 function freshLine():Line{const line:Line={notes:null};for(const f of cfg.fields)line[f.key]=f.options?.[0]??(f.type==="number"?(f.key==="quantity"||f.key==="requiredQuantity"?1:0):f.type==="datetime-local"?(event?.eventDateUtc??new Date().toISOString()):null);if(kind==="staffing-plans"){line.shiftEndUtc=new Date(new Date(event!.eventDateUtc).getTime()+4*3600000).toISOString();}if(kind==="equipment-plans"){line.neededUntilUtc=new Date(new Date(event!.eventDateUtc).getTime()+4*3600000).toISOString();}return line;}
 function fields(line:Line,onChange:(l:Line)=>void,editing=false){return <div className="co-form-grid">{cfg.fields.some(f=>f.type==="employee")&&<label>Search employees<input value={employeeSearch} onChange={e=>setEmployeeSearch(e.target.value)} placeholder="Name or employee number"/><small>First 50 matches. Narrow the search to find an employee.</small>{employeeError&&<span role="alert">{employeeError}</span>}</label>}{cfg.fields.filter(f=>!editing||!["role","equipmentType","equipmentName"].includes(f.key)).map(f=><label key={f.key}>{f.label}{f.options||f.type==="employee"?<select aria-label={f.label} required={f.required} value={String(line[f.key]??"")} onChange={e=>onChange({...line,[f.key]:e.target.value||null})}><option value="">{f.type==="employee"?"Unassigned":"Select"}</option>{f.options?f.options.map(v=><option value={v} key={v}>{humanize(v)}</option>):<>{line[f.key]&&!employees.some(e=>e.id===line[f.key])&&<option value={String(line[f.key])}>{String(line.employeeName??line.responsibleEmployeeName??"Current assignment")}</option>}{employees.map(e=><option key={e.id} value={e.id}>{e.fullName??e.displayName??e.employeeNo??"Employee"}</option>)}</>}</select>:<input required={f.required} type={f.type??"text"} min={f.min} step={f.type==="number"?"0.01":undefined} value={f.type==="datetime-local"?toDateTimeInput(String(line[f.key]??"")):line[f.key]??""} onChange={e=>onChange({...line,[f.key]:f.type==="number"?Number(e.target.value):f.type==="datetime-local"?(e.target.value?new Date(e.target.value).toISOString():null):e.target.value})}/>}</label>)}</div>;}
 function validate(lines:Line[]){for(const l of lines){if(l.shiftStartUtc&&l.shiftEndUtc&&new Date(String(l.shiftEndUtc))<=new Date(String(l.shiftStartUtc)))return "Shift end must be after shift start.";if(l.neededFromUtc&&l.neededUntilUtc&&new Date(String(l.neededUntilUtc))<=new Date(String(l.neededFromUtc)))return "Equipment return time must be after its start time.";}return "";}
 if(!event)return <section className="co-card"><p className="co-empty">Confirm an accepted quotation to manage staffing, production and billing.</p></section>;
 return <section className="co-workspace co-documents"><section className="co-card">{!canManage&&<p className="co-notice">View only. Your role needs {cfg.permission} to create or change these documents.</p>}<header className="co-toolbar"><div className="co-view">{kinds.map(k=><button key={k} disabled={busy} aria-pressed={kind===k} onClick={()=>{if(!guard.confirmDiscard())return;setKind(k);setMessage("");}}>{configs[k].label}</button>)}</div><button className="co-primary" disabled={busy||!canManage} onClick={()=>{setNotes("");setExtra({actualGuestCount:event.guestCount,destination:event.venueName,vehicleNo:"",plannedDispatchAtUtc:event.eventDateUtc,overProductionPercent:5});setDraft(kind==="production-plans"||kind==="final-bills"?[]:[freshLine()]);}}>+ {kind==="final-bills"?"New bill":kind==="dispatches"?"New dispatch":"New plan"}</button></header>
 {error&&<p className="co-notice" role="alert">{error}</p>}{message&&<p className="co-notice" role="status">{message}</p>}
 <div className="co-toolbar"><label>Document<select aria-label="Operational document" disabled={busy} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select document</option>{docs.map(d=><option value={d.id} key={d.id}>{d.planNo??d.billNo??d.dispatchNo} · {humanize(d.status)}</option>)}</select></label><button disabled={busy||loading} onClick={()=>setRevision(v=>v+1)}>Refresh documents</button></div>
 {doc?<><div className="co-toolbar"><h2>{doc.planNo??doc.billNo??doc.dispatchNo}</h2><span className="co-pill">{humanize(doc.status)}</span>{kind==="final-bills"&&<button onClick={()=>printDocument("Invoice "+doc.billNo,["Status: "+humanize(doc.status),"Customer: "+event.customerName,"Event: "+event.eventNo,"Date: "+(doc.billDateUtc?new Date(doc.billDateUtc).toLocaleDateString():"Not recorded"),"Contract: "+formatCurrency(doc.contractAmount??0),"Guest adjustment: "+formatCurrency(doc.guestCountAdjustmentAmount??0),"Discount: "+formatCurrency(doc.discountAmount??0),"Subtotal: "+formatCurrency(doc.subtotalAmount??0),"Tax: "+formatCurrency(doc.taxAmount??0),"Total: "+formatCurrency(doc.grandTotalAmount??0),"Deposit paid: "+formatCurrency(doc.depositPaidAmount??0),"Payments received: "+formatCurrency(doc.paymentsReceivedAmount??0),"Refund: "+formatCurrency(doc.refundAmount??0),"Balance due: "+formatCurrency(doc.balanceDueAmount??0)],["Description","Quantity","Unit price","Amount"],doc.lines.map(l=>[String(l.description??""),String(l.quantity??""),formatCurrency(Number(l.unitPrice??0)),formatCurrency(Number(l.amount??0))]))}>Print invoice</button>}{kind==="final-bills"&&<strong>Total {formatCurrency(doc.grandTotalAmount??0)} · Due {formatCurrency(doc.balanceDueAmount??0)}</strong>}</div><div className="co-table-wrap"><table className="co-table"><thead><tr><th>Item / role</th><th>Assignment / quantity</th><th>Status / amount</th><th>Actions</th></tr></thead><tbody>{doc.lines.map((l,i)=><tr key={String(l.id??i)}><td>{l.roleName??l.menuItemName??l.equipmentName??l.description??"Line"}<small>{l.notes}</small></td><td>{l.employeeName??l.responsibleEmployeeName??l.plannedQuantity??l.requiredQuantity??l.quantity??"Unassigned"}</td><td>{kind==="final-bills"?formatCurrency(Number(l.amount??0)):humanize(String(l.status??""))}</td><td><div className="co-actions">{!["final-bills","dispatches"].includes(kind)&&<button disabled={busy||!canManage||["cancelled","completed"].includes(doc.status)} onClick={()=>setEditLine({...l})}>Edit</button>}{cfg.states.length>0&&<select aria-label={"Status for line "+(i+1)} disabled={busy||!canManage||doc.status==="cancelled"} value={String(l.status??"")} onChange={e=>{const status=e.target.value;void mutate(()=>http.post(path+"/"+doc.id+"/lines/"+l.id+"/status",{status}),"Line status updated.");}}>{cfg.states.map(s=><option value={s} key={s}>{humanize(s)}</option>)}</select>}</div></td></tr>)}</tbody></table></div>
 <footer className="co-toolbar"><span>{doc.notes}</span><div className="co-actions">{kind==="final-bills"&&doc.status==="draft"&&<button disabled={busy||!hasPermission("catering.billing.approve")} onClick={()=>setConfirm({action:"approve",label:"Approve bill"})}>Approve bill</button>}{kind==="final-bills"&&doc.status==="approved"&&<button disabled={busy||!canManage} onClick={()=>setConfirm({action:"issue",label:"Issue bill"})}>Issue bill</button>}{kind==="dispatches"&&["draft","ready"].includes(doc.status)&&<button disabled={busy||!canManage} onClick={()=>setConfirm({action:"dispatch",label:"Dispatch delivery"})}>Dispatch</button>}{kind==="dispatches"&&doc.status==="dispatched"&&<button disabled={busy||!canManage} onClick={()=>setConfirm({action:"deliver",label:"Confirm delivery"})}>Mark delivered</button>}{!["cancelled","issued","delivered"].includes(doc.status)&&<button disabled={busy||!canManage} onClick={()=>{setReason("");setConfirm({action:"cancel",label:"Cancel document"});}}>Cancel document</button>}</div></footer></>:<p className="co-empty">{loading?"Loading documents...":"No documents yet. Create one for this event."}</p>}</section>
 {(draft||editLine||confirm)&&<div className="co-modal-backdrop"><section role="dialog" aria-modal="true" aria-label={confirm?.label??(editLine?"Edit line":"New "+cfg.label.toLowerCase())} className="co-modal"><form onSubmit={e=>{e.preventDefault();if(confirm&&doc){void mutate(()=>http.post(path+"/"+doc.id+"/"+confirm.action,confirm.action==="cancel"?{reason:reason.trim()}:{}),confirm.label+" saved.");return;}if(editLine&&doc){const invalid=validate([editLine]);if(invalid){setError(invalid);return;}void mutate(()=>http.put(path+"/"+doc.id+"/lines/"+editLine.id,editLine),"Line saved.");return;}if(draft){const invalid=validate(draft);if(invalid){setError(invalid);return;}const body=kind==="production-plans"?{overProductionPercent:Number(extra.overProductionPercent),activate,notes}:kind==="dispatches"?{...extra,markReady:activate,notes,lines:draft}:kind==="final-bills"?{actualGuestCount:Number(extra.actualGuestCount),notes,lines:draft}:{activate,notes,lines:draft};void mutate(()=>http.post(path,body),"Document created.");}}}><header className="co-toolbar"><h2>{confirm?.label??(editLine?"Edit line":"New "+cfg.label.toLowerCase())}</h2><button type="button" disabled={busy} onClick={closeDraft}>Close</button></header><fieldset disabled={busy}>
 {confirm?<><p>Apply this action to {doc?.planNo??doc?.billNo??doc?.dispatchNo}?</p>{confirm.action==="cancel"&&<label>Cancellation reason<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>}</>:editLine?fields(editLine,setEditLine,true):<>
 {kind==="production-plans"&&<label>Over-production %<input type="number" min="0" max="100" required step="0.1" value={extra.overProductionPercent??0} onChange={e=>setExtra({...extra,overProductionPercent:Number(e.target.value)})}/></label>}
 {kind==="final-bills"&&<label>Actual guests<input type="number" min="0" required value={extra.actualGuestCount??event.guestCount} onChange={e=>setExtra({...extra,actualGuestCount:Number(e.target.value)})}/></label>}
 {kind==="dispatches"&&<div className="co-form-grid"><label>Destination<input required value={extra.destination??""} onChange={e=>setExtra({...extra,destination:e.target.value})}/></label><label>Vehicle registration<input value={extra.vehicleNo??""} onChange={e=>setExtra({...extra,vehicleNo:e.target.value})}/></label><label>Dispatch time<input required type="datetime-local" value={toDateTimeInput(String(extra.plannedDispatchAtUtc??""))} onChange={e=>setExtra({...extra,plannedDispatchAtUtc:e.target.value?new Date(e.target.value).toISOString():null})}/></label></div>}
 {draft?.map((l,i)=><section className="co-editor-section" key={i}>{fields(l,next=>setDraft(rows=>rows!.map((r,j)=>i===j?next:r)))}<button type="button" onClick={()=>setDraft(rows=>rows!.filter((_,j)=>i!==j))}>Remove line</button></section>)}
 {kind!=="production-plans"&&<button type="button" onClick={()=>setDraft(rows=>[...rows!,freshLine()])}>+ Add {kind==="final-bills"?"charge":"line"}</button>}
 {kind!=="final-bills"&&<label className="co-check"><input type="checkbox" checked={activate} onChange={e=>setActivate(e.target.checked)}/>{kind==="dispatches"?"Mark ready":"Activate plan"}</label>}<label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></>}
 </fieldset>{error&&<p className="co-notice" role="alert">{error}</p>}<footer className="co-toolbar"><span>Changes are saved against {event.eventNo}.</span><button className="co-primary" disabled={busy||(!editLine&&!confirm&&kind!=="production-plans"&&kind!=="final-bills"&&!draft?.length)}>{busy?"Saving...":confirm?"Confirm action":"Save"}</button></footer></form></section></div>}
 </section>;
}
