import { CateringItemCostPreview } from "./CateringItemCostPreview";
import { Select } from "../../../components/ui/select";
import { CateringItemRecipeEditor } from "./CateringItemRecipeEditor";
import { StateMessage } from "../../../components/ui/Feedback";
import "../pages/catering-interactions.css";
import { CatalogCollection } from "./CatalogCollection";
import "./package-catalog.css";
import { useDialogFocus } from "../components/useDialogFocus";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { http } from "../../../api/http";
import { useAuth } from "../../../auth/AuthProvider";
import { readApiError } from "../sales/ui";
import { formatCurrency as money } from "../../../shared/currency/currencyFormat";
import { useUnsavedChanges } from "../components/useUnsavedChanges";
type Line={name?:string;itemId:string;quantity:number;perGuest:boolean;additionalCharge:number};
type Section={name:string;rule:string;selectCount:number;substitutionRequiresApproval:boolean;items:Line[]};
export type Offering={pricingSource?:string;category:string;serviceTier:string;pricingMode:string;fixedPrice:number;taxPercent:number;serviceChargePercent:number;approvedMarginPercent:number;effectiveDate:string|null;expiryDate:string|null;companyWide:boolean;archived:boolean;imageUrl:string|null;customerDescription:string|null;inclusions:string|null;exclusions:string|null;terms:string|null;notes:string|null;sections:Section[]};
export type CateringPackage={id?:string;branchId:string;packageNo?:string;name:string;description:string|null;pricePerPerson:number;minimumGuests:number|null;maximumGuests:number|null;isActive:boolean;sections:{menuItems:{menuItemId:string;menuItemName?:string;quantityPerGuest:number;isOptional:boolean;sortOrder:number}[]}[];offering:Offering|null;catalogVersion:number;changeReason?:string;packageCode?:string};
type Item={updatedAt?:string|null;id?:string;branchId:string|null;code:string;name:string;description:string|null;itemType:string;estimatedUnitCost:number;sellingPrice:number;isActive:boolean;recipeId:string|null;inventoryItemId:string|null;uomId:string|null;supplierId:string|null;consumptionLocationId?:string|null};
type Resource={id:string;name:string;baseUomId?:string;units?:string[]};
const freshSection=():Section=>({name:"Main courses",rule:"All",selectCount:1,substitutionRequiresApproval:false,items:[]});
const freshOffering=():Offering=>({pricingSource:"MenuItems",category:"Lunch",serviceTier:"Custom",pricingMode:"PerPerson",fixedPrice:0,taxPercent:15,serviceChargePercent:0,approvedMarginPercent:30,effectiveDate:null,expiryDate:null,companyWide:false,archived:false,imageUrl:null,customerDescription:null,inclusions:null,exclusions:null,terms:null,notes:null,sections:[freshSection()]});
export function PackagesScreen({companyId,branchId}:{companyId:string;branchId:string}){
 const {hasPermission}=useAuth();const manage=hasPermission("catering.manage"),approve=hasPermission("catering.approve");
 const base="/companies/"+companyId+"/catering",catalog=base+"/catalog";
 const [rows,setRows]=useState<CateringPackage[]>([]),[items,setItems]=useState<Item[]>([]),[rawResources,setResources]=useState<Record<string,Resource[]>>({});
 const resources=useMemo<Record<string,Resource[]>>(()=>{
   const byName=(a:Resource,b:Resource)=>a.name.trim().localeCompare(b.name.trim(),undefined,{sensitivity:"base",numeric:true})||a.id.localeCompare(b.id);
   return {...rawResources,inventory:[...(rawResources.inventory??[])].sort(byName),recipes:[...(rawResources.recipes??[])].sort(byName)};
 },[rawResources]);
 const [draft,setDraft]=useState<CateringPackage|null>(null),[item,setItem]=useState<Item|null>(null),[tab,setTab]=useState("packages"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[revision,setRevision]=useState(0);
 const [recipeItem,setRecipeItem]=useState<Item|null>(null);
 const [versionConflict,setVersionConflict]=useState(false);
 const [itemSearch,setItemSearch]=useState("");
 const [undo,setUndo]=useState<{offering:Offering;message:string}|null>(null);
 const requestScope=useRef(0);
 const [loading,setLoading]=useState(true),[success,setSuccess]=useState("");
 const [guests,setGuests]=useState(100),[report,setReport]=useState<Record<string,unknown>|null>(null),[history,setHistory]=useState<{version:number;action:string;reason:string;createdAt:string;createdBy:string}[]|null>(null);
 useEffect(()=>{if(report||history)document.getElementById(report?"pk-estimate":"pk-history")?.scrollIntoView({block:"start"});},[report,history]);
 useEffect(()=>{if(!draft){setVersionConflict(false);setUndo(null);setItemSearch("");}},[draft]);
 useEffect(()=>setRecipeItem(null),[companyId,branchId]);
 const guard=useUnsavedChanges(!!draft||!!item);
 useDialogFocus(!!draft||!!item,busy,()=>{if(guard.confirmDiscard()){setDraft(null);setItem(null);}});
 useEffect(()=>{const scope=++requestScope.current;const c=new AbortController();setVersionConflict(false);setDraft(null);setItem(null);setError("");setLoading(true);
 if(!branchId){setLoading(false);return;}
 Promise.all([http.get(base+"/packages",{params:{branchId,includeInactive:true},signal:c.signal}),http.get(catalog+"/items",{params:{branchId},signal:c.signal}),http.get(catalog+"/resources",{params:{branchId},signal:c.signal})]).then(([p,i,r])=>{if(c.signal.aborted||scope!==requestScope.current)return;setRows(p.data);setItems(i.data);setResources(r.data);}).catch(e=>{if(!c.signal.aborted)setError(readApiError(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[companyId,branchId,revision]);
 async function run(action:()=>Promise<unknown>,reload=true){if(busy)return;setBusy(true);setError("");try{await action();if(reload){setRevision(x=>x+1);setSuccess("Your changes have been saved.");}}catch(e){setError(readApiError(e));}finally{setBusy(false);}}
 async function openPackage(id:string,reload=false){
  if(busy|| (reload&&!guard.confirmDiscard()))return;
  const scope=requestScope.current;setBusy(true);setError("");
  try{const {data}=await http.get<CateringPackage>(base+"/packages/"+id);
   if(scope!==requestScope.current)return;
   if(!Number.isInteger(data.catalogVersion))throw new Error("Package version is unavailable. Refresh the app after restarting the API.");
   setRows(rows=>rows.map(row=>row.id===id?data:row));setDraft({...data,offering:{...(data.offering??freshOffering()),pricingSource:"MenuItems"}});setVersionConflict(false);
  }catch(e){if(scope===requestScope.current)setError(readApiError(e,"Unable to load the latest package."));}finally{setBusy(false);}
 }
 const change=(p:Partial<CateringPackage>)=>{setUndo(null);setDraft(d=>d?{...d,...p}:d);};
 const offering=(p:Partial<Offering>)=>change({offering:{...draft!.offering!,...p}});
 const section=(n:number,p:Partial<Section>)=>offering({sections:draft!.offering!.sections.map((s,i)=>i===n?{...s,...p}:s)});
 const line=(n:number,j:number,p:Partial<Line>)=>section(n,{items:draft!.offering!.sections[n].items.map((x,i)=>i===j?{...x,...p}:x)});
 function removeLine(n:number,j:number){const before=draft!.offering!;section(n,{items:before.sections[n].items.filter((_,i)=>i!==j)});setUndo({offering:before,message:"Item removed from this package."});}
 function removeSection(n:number){const before=draft!.offering!;offering({sections:before.sections.filter((_,i)=>i!==n)});setUndo({offering:before,message:"Section removed from this package."});}
 async function save(e:FormEvent){e.preventDefault();if(!draft||busy||versionConflict)return;
  if(!draft.offering?.sections.length||draft.offering.sections.some(s=>!s.items.length)){setError("Add at least one catering item to every section before saving. Remove any unused sections.");document.getElementById("pk-composition")?.scrollIntoView({block:"start"});return;}
  setBusy(true);setError("");
  try{if(draft.id&&!Number.isInteger(draft.catalogVersion)){setVersionConflict(true);setError("Package version is missing. Load the latest version before saving.");return;}
   const payload={...draft,expectedVersion:draft.catalogVersion,sections:[]};await(draft.id?http.put(base+"/packages/"+draft.id,payload):http.post(base+"/packages",payload));
   guard.markSaved();setSuccess("Package saved. Existing approved quotations keep their original snapshot.");setDraft(null);setVersionConflict(false);setRevision(x=>x+1);
  }catch(e){const failure=e as {response?:{status?:number;data?:{code?:string}}};if(failure.response?.data?.code==="PackageVersionConflict"||failure.response?.data?.code==="PackageVersionRequired"||failure.response?.data?.code==="RecordChanged")setVersionConflict(true);setError(readApiError(e));}finally{setBusy(false);}
 }
 const freshItem=():Item=>({branchId,code:"",name:"",description:null,itemType:"Food",estimatedUnitCost:0,sellingPrice:0,isActive:true,recipeId:null,inventoryItemId:null,uomId:null,supplierId:null,consumptionLocationId:null});
 const estimateGuests=Math.max(1,guests);
 const included=draft?.offering?.sections.flatMap(s=>s.rule==="AddOn"?[]:s.rule==="Choose"?s.items.slice(0,s.selectCount):s.items)??[];
 const draftCost=included.reduce((sum,l)=>sum+(items.find(i=>i.id===l.itemId)?.estimatedUnitCost??0)*l.quantity*(l.perGuest?estimateGuests:1),0);
 const draftSale=included.reduce((sum,l)=>sum+(items.find(i=>i.id===l.itemId)?.sellingPrice??0)*l.quantity*(l.perGuest?estimateGuests:1),0)+included.reduce((sum,l)=>sum+l.additionalCharge*(l.perGuest?estimateGuests:1),0);
 const draftMargin=draftSale>0?(draftSale-draftCost)/draftSale*100:0;
 const missingCosts=included.filter(l=>!items.some(i=>i.id===l.itemId&&i.estimatedUnitCost>0)).length;
 const targetMargin=draft?.offering?.approvedMarginPercent??30;
 const extraCharges=included.reduce((sum,l)=>sum+l.additionalCharge*(l.perGuest?estimateGuests:1),0);
 const suggestedTotal=included.length>0&&missingCosts===0&&targetMargin>=0&&targetMargin<100?draftCost/(1-targetMargin/100):null;
 const suggestedBase=suggestedTotal===null?null:Math.ceil(Math.max(0,suggestedTotal-extraCharges)/(draft?.offering?.pricingMode==="Fixed"?1:estimateGuests)*100-1e-8)/100;

 function newRecord(){setError("");setSuccess("");if(tab==="items")setItem(freshItem());else setDraft({branchId,name:"",description:null,pricePerPerson:0,minimumGuests:1,maximumGuests:null,isActive:false,sections:[],offering:freshOffering(),catalogVersion:0});}
 async function packageAction(r:CateringPackage,action:string){
  if(action==="approve"&&!window.confirm("Approve "+r.name+" revision "+r.catalogVersion+"? Review its items, pricing and terms before approving."))return;
  await run(async()=>{
   const url=catalog+"/packages/"+r.id+"/"+action;
   if(action==="estimate")setReport({...((await http.post(url,{guests})).data),guestCount:guests,packageName:r.name});
   else if(action==="history")setHistory((await http.get(url)).data);
   else await http.post(url,action==="approve"?{expectedVersion:r.catalogVersion}:undefined);
  },action!=="estimate"&&action!=="history");
 }
 return <section className="co-workspace pk-workspace">
 {!branchId&&<p className="co-notice">Select a branch to manage its catering catalog.</p>}{error&&!draft&&!item&&<StateMessage tone="error">{error}</StateMessage>}{success&&<div className="pk-success ci-feedback" role="status"><span>{success}</span><button aria-label="Dismiss success message" onClick={()=>setSuccess("")}>Dismiss</button></div>}
 <CatalogCollection onRecipe={manage&&hasPermission("recipes.manage")?setRecipeItem:undefined} rows={rows} items={items} tab={tab} setTab={setTab} loading={loading} busy={busy} manage={manage} approve={approve} branchId={branchId} guests={guests} setGuests={setGuests} onNew={newRecord} onRefresh={()=>setRevision(x=>x+1)} onEdit={id=>void openPackage(id)} onItem={value=>{setError("");setItem(value);}} onAction={(r,action)=>void packageAction(r,action)} onSeed={kind=>void run(()=>http.post(base+"/packages/"+kind,{branchId}))}/>
 {report&&<section id="pk-estimate" className="co-card pk-estimate" aria-label="Package cost estimate">{Number(report.missingCostCount)>0&&<p role="alert" className="co-notice">Some items have no estimated cost. Complete their costs before relying on this margin.</p>}<h2>{String(report.packageName)} — estimated cost for {Number(report.guestCount)} guests</h2><p>Choice sections use their first options for this preview; final quotations use the selected items.</p><div className="pk-estimate-grid">{["foodCost","serviceCost","totalCost","sellingPrice","grossProfit","tax","serviceCharge"].map(k=><p key={k}>{k.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())}: <strong>{money(Number(report[k]))}</strong></p>)}</div><p>Margin: {Number(report.margin).toFixed(1)}%</p><div className="pk-suggested-price"><div><small>Suggested selling price before tax & service charge</small><strong>{report.suggestedSellingPrice==null?"Complete costing and set a margin below 100%":money(Number(report.suggestedSellingPrice))}</strong>{report.suggestedPricePerPerson!=null&&<p>{money(Number(report.suggestedPricePerPerson))} per person · {Number(report.targetMarginPercent)}% target margin</p>}</div></div>{!!report.belowApprovedMargin&&<p role="alert" className="co-notice">Below the approved margin. Review the package price or costs.</p>}<button onClick={()=>setReport(null)}>Close estimate</button></section>}
 {history&&<section id="pk-history" className="co-card"><h2>Package audit history</h2>{!history.length&&<p>No revision history is available for this package.</p>}{history.map(h=><p key={h.version}>v{h.version} · {h.action} · {new Date(h.createdAt).toLocaleString()} · {h.createdBy} · {h.reason}</p>)}<button onClick={()=>setHistory(null)}>Close history</button></section>}
 {draft&&<div className="co-modal-backdrop"><section className="co-modal" role="dialog" aria-modal="true" aria-label="Package editor"><form onSubmit={save} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter"){e.preventDefault();if(!busy)e.currentTarget.requestSubmit();}}}><header className="co-toolbar"><h2>{draft.id?"Edit":"Create"} package</h2><button type="button" disabled={busy} onClick={()=>{if(guard.confirmDiscard())setDraft(null);}}>Close</button></header><nav className="pk-editor-nav" aria-label="Package editor sections">{[["details","01 · Identity"],["composition","02 · Menu composition"],["commercial","03 · Commercial rules"],["presentation","04 · Guest experience"]].map(([id,label])=><button key={id} type="button" onClick={()=>document.getElementById("pk-"+id)?.scrollIntoView({block:"start"})}>{label}</button>)}</nav>{undo&&<div className="ci-undo" role="status"><span>{undo.message}</span><button type="button" disabled={busy} onClick={()=>offering(undo.offering)}>Undo removal</button></div>}<fieldset disabled={busy||!manage}><section className="pk-editor-section" id="pk-details"><h3>Package identity</h3><p>A clear name and service tier help your team find the right offering for every occasion.</p><div className="co-form-grid">
 <label>Name<input required maxLength={150} value={draft.name} onChange={e=>change({name:e.target.value})}/></label><label>Code<input maxLength={40} disabled={!!draft.id} placeholder="Automatic if blank" value={draft.packageCode??draft.packageNo??""} onChange={e=>change({packageCode:e.target.value})}/></label>
 <label>Category<input required list="catering-categories" value={draft.offering!.category} onChange={e=>offering({category:e.target.value})}/><datalist id="catering-categories">{["Breakfast","Lunch","Dinner","Coffee Break","Cocktail","Wedding"].map(x=><option key={x}>{x}</option>)}</datalist></label>
 <label>Service tier<select value={draft.offering!.serviceTier} onChange={e=>offering({serviceTier:e.target.value})}>{["Bronze","Gold","Premium","Custom"].map(x=><option key={x}>{x}</option>)}</select></label>
 </div></section><section className="pk-editor-section" id="pk-composition"><h3>Menu composition</h3><div className="ci-composition-tools"><label>Find catering items<input type="search" value={itemSearch} placeholder="Search by name or item code…" onChange={e=>setItemSearch(e.target.value)}/></label><span>{draft.offering!.sections.length} sections · {draft.offering!.sections.reduce((n,s)=>n+s.items.length,0)} item entries</span></div><p>Organize courses, guest choices and optional enhancements. Costs scale by the guest count below. Choice previews use the first options; optional add-ons are excluded.</p>
 <div className="pk-cost-summary"><label>Estimate for guests<input type="number" min="1" value={guests} onChange={e=>setGuests(Math.max(1,Math.floor(Number(e.target.value)||1)))}/></label><div><small>Estimated cost</small><strong>{money(draftCost)}</strong></div><div><small>Selling price before tax</small><strong>{money(draftSale)}</strong></div><div><small>Gross margin</small><strong>{draftMargin.toFixed(1)}%</strong></div></div>
 <div className="pk-suggested-price"><div><small>Margin target reference · {targetMargin}% target margin</small><strong>{suggestedBase===null?"Complete costing to calculate":money(suggestedBase)}{suggestedBase!==null&&<span> / {draft.offering!.pricingMode==="Fixed"?"package":"person"}</span>}</strong><p>Cost ÷ (1 − target margin). Before tax and service charge; included extra charges are deducted from the suggested base price. Optional add-ons are excluded.</p>{targetMargin>=100&&<p role="alert">Set the target margin below 100% to calculate a suggested price.</p>}</div></div>
 {draft.id&&!approve&&<p className="pk-pricing-help">Package prices are calculated from catering item selling prices. Changes to an existing package price require an authorized approver and a reason.</p>}
 {missingCosts>0&&<p role="alert" className="co-notice">{missingCosts} included item entries need estimated costs. Complete them before relying on this margin.</p>}
 {draftMargin<draft.offering!.approvedMarginPercent&&<p role="alert" className="co-notice">Below the approved margin of {draft.offering!.approvedMarginPercent}%. Review the package price or costs.</p>}
{draft.offering!.sections.map((s,n)=><section className="co-editor-section" key={n}><div className="co-form-grid"><label>Section name<input required value={s.name} onChange={e=>section(n,{name:e.target.value})}/></label><label>Selection rule<select value={s.rule} onChange={e=>section(n,{rule:e.target.value})}><option value="All">Include all</option><option value="Choose">Choose a set number</option><option value="AddOn">Optional add-ons</option></select></label>{s.rule==="Choose"&&<label>Select count<input type="number" min="1" max={s.items.length} value={s.selectCount} onChange={e=>section(n,{selectCount:Number(e.target.value)})}/></label>}<label className="co-check"><input type="checkbox" checked={s.substitutionRequiresApproval} onChange={e=>section(n,{substitutionRequiresApproval:e.target.checked})}/>Substitutions require approval</label></div>
 {!s.items.length&&<p className="ci-help">This section is empty. Use “+ Catering item” below to start building the menu.</p>}{s.items.map((l,j)=><div className="co-menu-line" key={j}><label>Catering item<select required value={l.itemId} onChange={e=>line(n,j,{itemId:e.target.value})}><option value="">Select catering item</option>{l.itemId&&!items.some(i=>i.id===l.itemId&&i.isActive)&&<option value={l.itemId}>{l.name??"Existing item"} (inactive)</option>}{items.filter(i=>i.isActive&&(!draft.offering!.companyWide||!i.branchId)&&(i.id===l.itemId||(i.name+" "+i.code).toLowerCase().includes(itemSearch.trim().toLowerCase()))).map(i=><option key={i.id} value={i.id} disabled={s.items.some((other,k)=>k!==j&&other.itemId===i.id)}>{i.name}</option>)}</select></label><label>Quantity<input required type="number" min=".001" step=".001" value={l.quantity} onChange={e=>line(n,j,{quantity:Number(e.target.value)})}/></label><label>Scaling<select value={l.perGuest?"guest":"fixed"} onChange={e=>line(n,j,{perGuest:e.target.value==="guest"})}><option value="guest">Per guest</option><option value="fixed">Fixed quantity</option></select></label><label>Extra charge ({l.perGuest?"per guest":"fixed"})<input type="number" min="0" step=".01" value={l.additionalCharge} onChange={e=>line(n,j,{additionalCharge:Number(e.target.value)})}/></label><button type="button" aria-label={"Remove "+(items.find(i=>i.id===l.itemId)?.name??"catering item")} onClick={()=>removeLine(n,j)}>Remove</button><div className="pk-line-cost"><span>Item selling price: <strong>{money(items.find(i=>i.id===l.itemId)?.sellingPrice??0)}</strong></span><span>Unit cost: <strong>{money(items.find(i=>i.id===l.itemId)?.estimatedUnitCost??0)}</strong></span><span>Cost for {l.quantity*(l.perGuest?estimateGuests:1)} units: <strong>{money((items.find(i=>i.id===l.itemId)?.estimatedUnitCost??0)*l.quantity*(l.perGuest?estimateGuests:1))}</strong></span>{s.rule==="AddOn"&&<span>Optional · excluded from base estimate</span>}</div></div>)}
 <div className="co-actions"><button type="button" onClick={()=>section(n,{items:[...s.items,{itemId:"",quantity:1,perGuest:true,additionalCharge:0}]})}>+ Catering item</button><button type="button" disabled={n===0} onClick={()=>{const next=[...draft.offering!.sections];[next[n-1],next[n]]=[next[n],next[n-1]];offering({sections:next});}}>Move up</button><button type="button" disabled={n===draft.offering!.sections.length-1} onClick={()=>{const next=[...draft.offering!.sections];[next[n],next[n+1]]=[next[n+1],next[n]];offering({sections:next});}}>Move down</button><button type="button" onClick={()=>removeSection(n)}>Remove section</button></div></section>)}
 <button type="button" onClick={()=>offering({sections:[...draft.offering!.sections,freshSection()]})}>+ Section</button></section><section className="pk-editor-section" id="pk-commercial"><h3>Commercial rules & availability</h3><p>Set pricing, guest limits and selling dates. New packages start inactive until you are ready to offer them.</p><div className="co-form-grid"><label>Pricing<select value={draft.offering!.pricingMode} onChange={e=>offering({pricingMode:e.target.value})}><option value="PerPerson">Per person</option><option value="Fixed">Fixed package</option></select></label>
 <label>Calculated base price (at minimum guests)<input readOnly value={money(included.reduce((sum,l)=>sum+(items.find(i=>i.id===l.itemId)?.sellingPrice??0)*l.quantity*(l.perGuest?Math.max(1,draft.minimumGuests??1):1),0)/(draft.offering!.pricingMode==="Fixed"?1:Math.max(1,draft.minimumGuests??1)))}/><small>Menu item price × quantity. Per-guest lines scale with attendance; fixed quantities are charged once. Extra charges, tax and service charge are separate. Final price uses selected choices and add-ons.</small></label>
 {(["taxPercent","serviceChargePercent","approvedMarginPercent"] as const).map(k=><label key={k}>{k.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())}<input type="number" min="0" max="100" step=".01" value={draft.offering![k]} onChange={e=>offering({[k]:Number(e.target.value)})}/></label>)}
 {(["minimumGuests","maximumGuests"] as const).map(k=><label key={k}>{k.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())}<input type="number" min="1" value={draft[k]??""} onChange={e=>change({[k]:e.target.value?Number(e.target.value):null})}/></label>)}
 {(["effectiveDate","expiryDate"] as const).map(k=><label key={k}>{k==="effectiveDate"?"Available from":"Available until"}<input type="date" value={draft.offering![k]?.slice(0,10)??""} onChange={e=>offering({[k]:e.target.value?e.target.value+"T00:00:00Z":null})}/></label>)}
 <label>Status<select value={draft.offering!.archived?"Archived":draft.isActive?"Active":"Inactive"} onChange={e=>change({isActive:e.target.value==="Active",offering:{...draft.offering!,archived:e.target.value==="Archived"}})}>{["Active","Inactive","Archived"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="co-check"><input type="checkbox" checked={draft.offering!.companyWide} onChange={e=>offering({companyWide:e.target.checked})}/>Company-wide availability</label>
 </div></section><section className="pk-editor-section" id="pk-presentation"><h3>The guest experience</h3><p>Describe the menu, what is included and the terms your customer will receive.</p><div className="co-form-grid"><label>Internal description<textarea maxLength={1000} value={draft.description??""} onChange={e=>change({description:e.target.value})}/></label>
 {(["customerDescription","imageUrl","inclusions","exclusions","terms","notes"] as const).map(k=><label key={k}>{k.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())}<textarea value={draft.offering![k]??""} onChange={e=>offering({[k]:e.target.value})}/></label>)}
 <label>Change / price override reason<textarea value={draft.changeReason??""} onChange={e=>change({changeReason:e.target.value})}/></label></div>
 </section></fieldset>{error&&<StateMessage tone="error">{error}</StateMessage>}{versionConflict&&<div className="co-notice"><p>Your draft is still here. Loading the latest version will ask before discarding it.</p><button type="button" disabled={busy} onClick={()=>void openPackage(draft.id!,true)}>Load latest version</button></div>}<button className="co-primary" disabled={busy||!manage||versionConflict}>{busy?"Saving package…":"Save package"}</button><p className="ci-save-hint">Save with Ctrl + Enter (⌘ + Enter on Mac). Changes are saved only when you choose Save package.</p></form></section></div>}
 {recipeItem&&<CateringItemRecipeEditor companyId={companyId} branchId={branchId} item={recipeItem} resources={resources} onClose={()=>setRecipeItem(null)} onSaved={()=>{setRecipeItem(null);setRevision(x=>x+1);setSuccess("Catering recipe saved as a new revision.");}}/>}
 {item&&<div className="co-modal-backdrop"><section className="co-modal" role="dialog" aria-modal="true" aria-label="Catering item editor"><form onSubmit={e=>{e.preventDefault();void run(async()=>{await(item.id?http.put(catalog+"/items/"+item.id,item):http.post(catalog+"/items",item));guard.markSaved();setItem(null);});}}><header className="co-toolbar"><h2>Catering item</h2><button type="button" disabled={busy} onClick={()=>{if(guard.confirmDiscard())setItem(null);}}>Close</button></header><fieldset disabled={busy||!manage}><div className="co-form-grid">
 {(["name","code","description"] as const).map(k=><label key={k}>{k}<input required={k!=="description"} value={item[k]??""} onChange={e=>setItem({...item,[k]:e.target.value})}/></label>)}<label>Type<select value={item.itemType} onChange={e=>setItem({...item,itemType:e.target.value})}>{["Food","Beverage","BulkProduction","Service","Equipment","Staffing","Transport","Decoration","Custom"].map(x=><option key={x}>{x}</option>)}</select></label>
 {(["estimatedUnitCost","sellingPrice"] as const).filter(k=>k!=="estimatedUnitCost"||(!item.recipeId&&!item.inventoryItemId)).map(k=><label key={k}>{k==="sellingPrice"?"Selling price":"Manual estimated cost (unlinked items only)"}<input disabled={k==="estimatedUnitCost"&&!!(item.recipeId||item.inventoryItemId)} required type="number" min="0" step=".01" value={item[k]} onChange={e=>setItem({...item,[k]:Number(e.target.value)})}/></label>)}
 {(["recipeId","inventoryItemId","uomId","supplierId"] as const).map((k,n)=><label key={k}>{["Recipe / production recipe","Inventory item","Unit of measure","Supplier"][n]}<select value={item[k]??""} onChange={e=>setItem({...item,[k]:e.target.value||null,...(k==="inventoryItemId"?{uomId:resources.inventory?.find(x=>x.id===e.target.value)?.baseUomId??null}:{})})}><option value="">None</option>{(resources[["recipes","inventory","units","suppliers"][n]]??[]).filter(r=>k!=="uomId"||!item.inventoryItemId||r.id===resources.inventory?.find(x=>x.id===item.inventoryItemId)?.baseUomId||resources.inventory?.find(x=>x.id===item.inventoryItemId)?.units?.includes(r.id)).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>)}
 <label>Consumption location<Select required value={item.consumptionLocationId??""} onChange={e=>setItem({...item,consumptionLocationId:e.target.value||null})}><option value="">Select consumption location</option>{(resources.consumptionLocations??[]).map(location=><option key={location.id} value={location.id}>{location.name}</option>)}</Select><small>Ingredients are reserved from this branch location. Company-wide items require this location to be authorized in each event branch.</small></label>
 <CateringItemCostPreview companyId={companyId} request={{branchId:item.branchId,consumptionLocationId:item.consumptionLocationId,recipeId:item.recipeId,inventoryItemId:item.inventoryItemId,uomId:item.uomId}}/><label className="co-check"><input type="checkbox" checked={item.isActive} onChange={e=>setItem({...item,isActive:e.target.checked})}/>Active</label><label className="co-check"><input type="checkbox" checked={!item.branchId} onChange={e=>setItem({...item,branchId:e.target.checked?null:branchId})}/>Company-wide item</label></div></fieldset>{error&&<p role="alert">{error}</p>}<button disabled={busy||!manage}>Save catering item</button></form></section></div>}
 </section>;
}
