services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurantfnb-admin
    ports:
      - "5173:80"
    depends_on:
      - api

  api:
    image: restaurantfnb-api:latest
    container_name: restaurantfnb-api
    ports:
      - "7216:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
