import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {http} from "../../../api/http";
import {Button} from "../../../components/ui/button";
import {Input} from "../../../components/ui/input";
import {Select} from "../../../components/ui/select";
import {Textarea} from "../../../components/ui/textarea";
import {useI18n} from "../../../i18n";
import {useHasPermission} from "../../../auth/usePermissions";
import {apiError,money,dateTime} from "./p2pShared";
import RequisitionDocuments from "./RequisitionDocuments";
type Data={request?:{id:string;version:string;status:string;category:string;reason:string;authorizedAmount:number;dueAtUtc:string;decisionReason?:string};rules:{id:string;definition:{name:string;category?:string;maximumAmount:number}}[];reviewers:{id:string;name:string}[];invoices:{id:string;internalNo:string}[];receipts:{id:string;grnNo:string}[];hasReceiptEvidence:boolean;actualCost:number;overdue:boolean;canDecide:boolean};
export default function EmergencyPurchasePanel({companyId,id,version,status}:{companyId:string;id:string;version:string;status:string}){
 const {tx}=useI18n(),canCreate=useHasPermission("purchasing.create");const [data,setData]=useState<Data|null>(null),[category,setCategory]=useState(""),[reason,setReason]=useState(""),[reviewer,setReviewer]=useState(""),[decisionReason,setDecisionReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const root=`/companies/${companyId}/procurement/purchase-orders/${id}/emergency`;
 async function load(){setData((await http.get<Data>(root)).data);}
 useEffect(()=>{let active=true;http.get<Data>(root).then(r=>{if(active)setData(r.data);}).catch(e=>{if(active)setError(apiError(e,"Unable to load emergency controls."));});return()=>{active=false;};},[companyId,id,version]);
 async function act(decision?:string){if(busy)return;setBusy(true);setError("");try{await http.post(decision?`${root}/decision`:root,decision?{version:data?.request?.version,decision,reason:decisionReason}:{category,reason,reviewerId:reviewer});await load();setDecisionReason("");}catch(e){setError(apiError(e,"Unable to save emergency review."));}finally{setBusy(false);}}
 return <details className="prq-panel" open={!!data?.request}><summary>{tx("Emergency purchasing authorization")}{data?.request?` · ${tx(data.request.status)}`:""}</summary>{error&&<p role="alert">{tx(error)}</p>}{data?.request&&<><p>{data.request.reason}</p><p>{tx("Authorized commitment")}: {money(data.request.authorizedAmount)} · {tx("Actual approved invoice cost")}: {money(data.actualCost)} · {tx("Review due")}: {dateTime(data.request.dueAtUtc)}</p>{data.overdue&&<p role="alert">{tx("Emergency review is overdue.")}</p>}{!data.hasReceiptEvidence&&<p>{tx("Supplier receipt evidence is missing.")}</p>}<p>{data.request.decisionReason}</p>{data.invoices.map(i=><p key={i.id}><Link to={`/procurement/supplier-invoices/${i.id}`}>{i.internalNo}</Link></p>)}<RequisitionDocuments companyId={companyId} id={data.request.id} documentType="emergency" editable={canCreate&&!["Reviewed","Rejected"].includes(data.request.status)} onChanged={()=>void load()}/>{data.canDecide&&["Pending","Authorized"].includes(data.request.status)&&<fieldset disabled={busy}><legend>{tx("Designated reviewer decision")}</legend><label>{tx("Decision reason")}<Textarea maxLength={1000} value={decisionReason} onChange={e=>setDecisionReason(e.target.value)}/></label>{data.request.status==="Pending"?<><Button disabled={!decisionReason.trim()} onClick={()=>void act("Authorize")}>{tx("Authorize emergency purchase")}</Button><Button variant="outline" disabled={!decisionReason.trim()} onClick={()=>void act("Reject")}>{tx("Reject")}</Button></>:<Button disabled={!decisionReason.trim()} onClick={()=>void act("CompleteReview")}>{tx("Complete actual-cost and evidence review")}</Button>}</fieldset>}</>}
 {canCreate&&status==="Draft"&&data?.request?.status!=="Reviewed"&&<fieldset disabled={busy}><legend>{tx(data?.request?"Request revised authorization":"Request emergency authorization")}</legend><p>{tx("The linked order reserves the approved requirement quantities. Normal receiving, invoice matching and payment controls still apply.")}</p>{data?.rules.map(r=><p key={r.id}>{r.definition.name} · {r.definition.category||tx("All categories")} · {tx("Maximum")}: {money(r.definition.maximumAmount)}</p>)}<label>{tx("Purchase category")}<Input maxLength={160} value={category} onChange={e=>setCategory(e.target.value)}/></label><label>{tx("Emergency reason")}<Textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>{tx("Designated authorizer")}<Select value={reviewer} onChange={e=>setReviewer(e.target.value)}><option value="">{tx("Select authorizer")}</option>{data?.reviewers.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</Select></label><Button disabled={!category.trim()||!reason.trim()||!reviewer} onClick={()=>void act()}>{tx("Request authorization")}</Button></fieldset>}</details>;
}
