import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {http} from "../../../api/http";
import {Button} from "../../../components/ui/button";
import {Input} from "../../../components/ui/input";
import {Select} from "../../../components/ui/select";
import {Textarea} from "../../../components/ui/textarea";
import {useHasPermission} from "../../../auth/usePermissions";
import {useI18n} from "../../../i18n";
import {apiError,money,qty} from "./p2pShared";
type Receipt={id:string;grnNo:string;status:string;fingerprint:string;lines:{id:string;lineNo:number;qty:number;unitCost:number}[]};
type Data={receipts:Receipt[];costs:{id:string;grnId:string;invoiceId:string;component:string;method:string;amount:number;reason:string;status:string;voidReason?:string}[];invoices:{id:string;internalNo:string;supplierInvoiceNo:string;baseAmount:number;paymentStatus:string}[]};
export default function LandedCostsPanel({companyId,id,version}:{companyId:string;id:string;version:string}){
 const {tx}=useI18n(),canAllocate=useHasPermission("purchasing.financeapprove");
 const [data,setData]=useState<Data>({receipts:[],costs:[],invoices:[]}),[receiptId,setReceipt]=useState(""),[invoiceId,setInvoice]=useState(""),[component,setComponent]=useState("Freight"),[method,setMethod]=useState("Value"),[amount,setAmount]=useState(""),[reason,setReason]=useState(""),[values,setValues]=useState<Record<string,string>>({}),[preview,setPreview]=useState<{lineId:string;amount:number}[]|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[requestId,setRequestId]=useState(()=>crypto.randomUUID());
 const root=`/companies/${companyId}/procurement`,receipt=data.receipts.find(x=>x.id===receiptId);
 const [correction,setCorrection]=useState<Record<string,string>>({});
 async function voidAllocation(costId:string){if(busy||!correction[costId]?.trim())return;setBusy(true);setError("");try{await http.post(`${root}/landed-costs/${costId}/void`,{reason:correction[costId]});await load();}catch(e){setError(apiError(e,"Unable to void the allocation."));}finally{setBusy(false);}}
 async function load(){setData((await http.get<Data>(`${root}/purchase-orders/${id}/landed-costs`)).data);}
 useEffect(()=>{let active=true;http.get<Data>(`${root}/purchase-orders/${id}/landed-costs`).then(r=>{if(active)setData(r.data);}).catch(e=>{if(active)setError(apiError(e,"Unable to load landed costs."));});return()=>{active=false;};},[companyId,id,version]);
 useEffect(()=>{setPreview(null);setRequestId(crypto.randomUUID());},[receiptId,invoiceId,component,method,amount,reason,values]);
 async function allocate(save:boolean){if(!receipt||busy)return;setBusy(true);setError("");try{const r=await http.post(`${root}/landed-costs${save?"":"/preview"}`,{id:requestId,grnId:receipt.id,invoiceId,component,method,amount:Number(amount),reason,receiptFingerprint:receipt.fingerprint,lines:receipt.lines.map(l=>({lineId:l.id,quantity:l.qty,value:l.qty*l.unitCost,weight:method==="Weight"?Number(values[l.id]||0):0,manualAmount:method==="Manual"?Number(values[l.id]||0):0}))});if(save){setPreview(null);setAmount("");setInvoice("");setRequestId(crypto.randomUUID());await load();}else setPreview(r.data.allocations);}catch(e){setError(apiError(e,"Unable to allocate landed costs."));}finally{setBusy(false);}}
 return <section className="prq-panel"><h2>{tx("Landed acquisition costs")}</h2><p>{tx("Allocate approved freight, handling and duties before posting the receipt. Amounts use company currency and exclude recoverable tax. Supplier-price comparisons keep the original unit price.")}</p>{error&&<p role="alert">{tx(error)}</p>}{data.costs.map(c=><p key={c.id}>{data.receipts.find(r=>r.id===c.grnId)?.grnNo} · {tx(c.component)} · {money(c.amount)} · {tx(c.method)} · <Link to={`/procurement/supplier-invoices/${c.invoiceId}`}>{tx("AP invoice")}</Link> · {c.reason} · {tx(c.status)}{c.voidReason&&<> · {c.voidReason}</>}{canAllocate&&c.status==="Allocated"&&["Draft","Approved","Reversed"].includes(data.receipts.find(r=>r.id===c.grnId)?.status||"")&&<span><label>{tx("Correction reason")}<Input value={correction[c.id]||""} onChange={e=>setCorrection(v=>({...v,[c.id]:e.target.value}))}/></label><Button disabled={busy||!correction[c.id]?.trim()} onClick={()=>void voidAllocation(c.id)}>{tx("Void allocation")}</Button></span>}</p>)}
 {canAllocate&&<fieldset disabled={busy}><legend>{tx("Preview cost allocation")}</legend><label>{tx("Receipt")}<Select value={receiptId} onChange={e=>{setReceipt(e.target.value);setValues({});}}><option value="">{tx("Choose a receipt")}</option>{data.receipts.filter(r=>["Draft","Approved"].includes(r.status)).map(r=><option key={r.id} value={r.id}>{r.grnNo} · {tx(r.status)}</option>)}</Select></label><label>{tx("Approved additional-cost invoice")}<Select value={invoiceId} onChange={e=>setInvoice(e.target.value)}><option value="">{tx("Choose an AP invoice")}</option>{data.invoices.filter(i=>!data.costs.some(c=>c.invoiceId===i.id&&c.status==="Allocated")).map(i=><option key={i.id} value={i.id}>{i.internalNo} · {i.supplierInvoiceNo} · {money(i.baseAmount)} · {tx(i.paymentStatus)}</option>)}</Select></label>
 <label>{tx("Component")}<Select value={component} onChange={e=>setComponent(e.target.value)}>{["Freight","Handling","Duties","Other"].map(x=><option key={x}>{x}</option>)}</Select></label><label>{tx("Allocation method")}<Select value={method} onChange={e=>setMethod(e.target.value)}>{["Quantity","Weight","Value","Manual"].map(x=><option key={x}>{x}</option>)}</Select></label><label>{tx("Amount in company currency")}<Input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label>
 {receipt?.lines.map(l=><div key={l.id}>{tx("Receipt line")} {l.lineNo} · {qty(l.qty)} × {money(l.unitCost)}{["Weight","Manual"].includes(method)&&<label>{tx(method==="Weight"?"Weight in kg":"Allocated amount")}<Input type="number" min="0" step={method==="Weight"?"0.001":"0.01"} value={values[l.id]||""} onChange={e=>setValues({...values,[l.id]:e.target.value})}/></label>}{preview&&<strong> · {money(preview.find(p=>p.lineId===l.id)?.amount||0)}</strong>}</div>)}
 <label>{tx("Allocation justification")}<Textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={!receipt||!invoiceId||!amount||!reason.trim()} onClick={()=>void allocate(false)}>{tx("Preview allocation")}</Button>{preview&&<Button onClick={()=>void allocate(true)}>{tx("Save reviewed allocation")}</Button>}</fieldset>}
 <p>{tx("Posted costs are retained. Corrections require an authorized GRN reversal and a replacement receipt; stock already consumed must be resolved before reversal.")}</p></section>;
}
