import {useEffect,useState} from "react";
import {http} from "../../../api/http";
import {PageHeader} from "../../../components/PageHeader";
import {Button} from "../../../components/ui/button";
import {Input} from "../../../components/ui/input";
import {Select} from "../../../components/ui/select";
import {Checkbox} from "../../../components/ui/checkbox";
import {useHasPermission} from "../../../auth/usePermissions";
import {useI18n} from "../../../i18n";
import {asItems,apiError,money,todayIso,useCompanyId} from "../components/p2pShared";
type Budget={id:string;name:string;from:string;to:string;branchId?:string;departmentId?:string;category?:string;amount:number;actual:number;openCommitments:number;available:number;action:string;ownerId:string;version:string;isActive:boolean};
const blank=():Budget=>({id:crypto.randomUUID(),name:"",from:todayIso(),to:`${new Date().getFullYear()}-12-31`,amount:0,actual:0,openCommitments:0,available:0,action:"Review",ownerId:"",version:"00000000-0000-0000-0000-000000000000",isActive:true});
export default function ProcurementBudgetsPage(){
  const {tx}=useI18n(),companyId=useCompanyId(),canManage=useHasPermission("purchasing.manage");
  const [rows,setRows]=useState<Budget[]>([]),[form,setForm]=useState<Budget>(blank),[error,setError]=useState(""),[busy,setBusy]=useState(false),[users,setUsers]=useState<{id:string;name:string}[]>([]),[branches,setBranches]=useState<{id:string;name:string}[]>([]),[departments,setDepartments]=useState<{id:string;name:string}[]>([]);
  const root=`/companies/${companyId}/procurement/budgets`;
  async function load(){setRows((await http.get<Budget[]>(root)).data);}
  useEffect(()=>{if(!companyId)return;void load().catch(e=>setError(apiError(e,"Unable to load purchasing budgets.")));if(canManage)void Promise.all([http.get<{id:string;name:string}[]>(`/companies/${companyId}/procurement/rules/users`).catch(()=>({data:[] as {id:string;name:string}[]})),http.get<{id:string;name:string}[]>(`/companies/${companyId}/branches`).catch(()=>({data:[] as {id:string;name:string}[]})),http.get<{id:string;name:string}[]>(`/companies/${companyId}/inventory-items/departments`)]).then(([u,b,d])=>{setUsers(u.data);setBranches(asItems(b.data));setDepartments(d.data);}).catch(e=>setError(apiError(e,"Unable to load budget owners and scopes.")));},[companyId,canManage]);
  async function save(){if(busy)return;setBusy(true);setError("");try{await http.post(root,{...form,branchId:form.branchId||null,departmentId:form.departmentId||null,category:form.category||null});await load();setForm(blank());}catch(e){setError(apiError(e,"Unable to save purchasing budget."));}finally{setBusy(false);}}
  return <main className="prq-page"><PageHeader title={tx("Purchasing budgets")} subtitle={tx("Actual approved invoices plus open order commitments, in company base currency.")}/>{error&&<p role="alert">{tx(error)}</p>}<p>{tx("Approved invoiced quantities reduce the remaining order commitment. Cancellation releases unreceived quantities; received goods awaiting invoices remain committed.")}</p>
    {rows.map(b=><section className="prq-panel" key={b.id}><h2>{b.name}</h2><p>{b.from} – {b.to} · {tx(b.action)} · {tx(b.isActive?"Active":"Inactive")}</p><dl><dt>{tx("Budget")}</dt><dd>{money(b.amount)}</dd><dt>{tx("Actual spending")}</dt><dd>{money(b.actual)}</dd><dt>{tx("Open commitments")}</dt><dd>{money(b.openCommitments)}</dd><dt>{tx("Available")}</dt><dd>{money(b.available)}</dd></dl>{canManage&&<Button variant="outline" onClick={()=>setForm(b)}>{tx("Revise budget")}</Button>}</section>)}
    {canManage&&<form className="prq-panel" onSubmit={e=>{e.preventDefault();void save();}}><h2>{tx("Configure budget")}</h2><div className="prq-form-grid"><label>{tx("Budget name")}<Input required maxLength={160} value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></label>{(["from","to"] as const).map(k=><label key={k}>{tx(k==="from"?"From":"To")}<Input required type="date" value={form[k]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></label>)}
      <label>{tx("Amount in base currency")}<Input required type="number" min={0} step="0.01" value={form.amount} onChange={e=>setForm(f=>({...f,amount:Number(e.target.value)}))}/></label><label>{tx("Branch")}<Select value={form.branchId??""} onChange={e=>setForm(f=>({...f,branchId:e.target.value||undefined}))}><option value="">{tx("All branches")}</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select></label><label>{tx("Department")}<Select value={form.departmentId??""} onChange={e=>setForm(f=>({...f,departmentId:e.target.value||undefined}))}><option value="">{tx("All departments")}</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</Select></label><label>{tx("Purchase category (blank for all)")}<Input maxLength={160} value={form.category??""} onChange={e=>setForm(f=>({...f,category:e.target.value}))}/></label><label>{tx("Budget owner")}<Select required value={form.ownerId} onChange={e=>setForm(f=>({...f,ownerId:e.target.value}))}><option value="">{tx("Select owner")}</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</Select></label><label>{tx("Overrun action")}<Select value={form.action} onChange={e=>setForm(f=>({...f,action:e.target.value}))}>{["Warn","Review","Block"].map(v=><option key={v}>{tx(v)}</option>)}</Select></label></div><label><Checkbox checked={form.isActive} onChange={e=>setForm(f=>({...f,isActive:e.target.checked}))}/>{tx("Active")}</label><Button type="submit" disabled={busy}>{tx("Save budget")}</Button></form>}
  </main>;
}
