import NegotiatedPriceHint from "../components/NegotiatedPriceHint";
import { useEffect,useRef,useState,type FormEvent } from "react";
import { Link,useNavigate,useParams } from "react-router-dom";
import { http } from "../../../api/http";
import { PageHeader } from "../../../components/PageHeader";
import { Button } from "../../../components/ui/button";
import { Input } from "../../../components/ui/input";
import { Select } from "../../../components/ui/select";
import { Textarea } from "../../../components/ui/textarea";
import { Checkbox } from "../../../components/ui/checkbox";
import { useHasPermission } from "../../../auth/usePermissions";
import { useI18n } from "../../../i18n";
import { inventoryItemsApi } from "../../inventoryMaster/items/api/inventoryItemsApi";
import type { InventoryItemDto } from "../../inventoryMaster/items/types";
import { suppliersApi,type SupplierLookup } from "../api/purchasingApi";
import { getPurchaseRequisition,type PurchaseRequisition } from "../api/procurementApi";
import { apiError,money,qty,todayIso,useCompanyId } from "../components/p2pShared";

type Requirement={requisitionId:string;requisitionLineId:string;requisitionNo:string;itemId?:string;itemName:string;uomId?:string;unit:string;quantity:number;toBaseFactor:number;specification?:string};
type QuoteLine={requisitionLineId:string;uomId?:string;unit:string;quantity:number;unitPrice:number;discountPercent:number;taxRatePercent:number;freight:number;baseQuantity:number;costPerBaseUnit:number;total:number};
type Offer={id:string;supplierId:string;supplierName:string;supplierReference:string;currencyCode:string;exchangeRate:number;validUntil:string;deliveryDate:string;paymentTermDays:number;isCurrent:boolean;notes:string;lines:QuoteLine[]};
type Rfq={id:string;branchId?:string;reference:string;responseDue:string;currencyCode:string;status:string;version:string;requirements:Requirement[];quotes:Offer[];awards:{id:string;justification:string;awardedAtUtc:string;lines:{quoteId:string;supplierId:string;requisitionLineId:string;quantity:number;comparisonAmount:number}[]}[]};
type OfferInput=Omit<QuoteLine,"unit"|"baseQuantity"|"costPerBaseUnit"|"total">&{include:boolean};
const unwrap=<T,>(data:T[]|{items:T[]})=>Array.isArray(data)?data:data.items;

export default function ProcurementQuotationsPage(){
  const companyId=useCompanyId(),{id}=useParams<{id:string}>(),navigate=useNavigate(),{tx}=useI18n();
  const canCreate=useHasPermission("purchasing.create"),root=`/companies/${companyId}/procurement/quotations`;
  const [requests,setRequests]=useState<Rfq[]>([]),[requisitions,setRequisitions]=useState<PurchaseRequisition[]>([]),[selected,setSelected]=useState<PurchaseRequisition|null>(null),[selectedId,setSelectedId]=useState("");
  const [checked,setChecked]=useState<string[]>([]),[responseDue,setResponseDue]=useState(todayIso(7)),[currency,setCurrency]=useState("ETB"),[row,setRow]=useState<Rfq|null>(null);
  const [suppliers,setSuppliers]=useState<SupplierLookup[]>([]),[items,setItems]=useState<InventoryItemDto[]>([]),[offerLines,setOfferLines]=useState<OfferInput[]>([]);
  const [offer,setOffer]=useState({supplierId:"",supplierReference:"",currencyCode:"ETB",exchangeRate:1,validUntil:todayIso(14),deliveryDate:todayIso(7),paymentTermDays:30,notes:""});
  const [award,setAward]=useState<Record<string,number>>({}),[justification,setJustification]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [comparisonExchangeRate,setComparisonExchangeRate]=useState(1),[createdOrders,setCreatedOrders]=useState<{id:string;poNo:string}[]>([]);
  async function createOrders(awardId:string){if(!row||busy)return;setBusy(true);setError("");try{setCreatedOrders((await http.post<{id:string;poNo:string}[]>(`${root}/${row.id}/awards/${awardId}/purchase-orders`,{comparisonExchangeRate})).data);}catch(e){setError(apiError(e,"Unable to create orders from the saved supplier selection."));}finally{setBusy(false);}}
  const createKey=useRef(crypto.randomUUID()),quoteKey=useRef(crypto.randomUUID()),awardKey=useRef(crypto.randomUUID());
  async function load(){
    if(id){const r=(await http.get<Rfq>(`${root}/${id}`)).data;setRow(r);return r;}
    const [r,a,s]=await Promise.all([http.get<Rfq[]>(root),http.get<PurchaseRequisition[]|{items:PurchaseRequisition[]}>(`/companies/${companyId}/procurement/requisitions`,{params:{status:"Approved",pageSize:100}}),http.get<PurchaseRequisition[]|{items:PurchaseRequisition[]}>(`/companies/${companyId}/procurement/requisitions`,{params:{status:"Sourcing",pageSize:100}})]);
    setRequests(r.data);setRequisitions([...unwrap(a.data),...unwrap(s.data)]);return null;
  }
  useEffect(()=>{if(!companyId)return;let active=true;setError("");void load().then(r=>{if(!active||!r)return;setOffer(f=>({...f,currencyCode:r.currencyCode}));setOfferLines(r.requirements.map(l=>({requisitionLineId:l.requisitionLineId,uomId:l.uomId,quantity:l.quantity,unitPrice:0,discountPercent:0,taxRatePercent:0,freight:0,include:true})));}).catch(e=>active&&setError(apiError(e,"Unable to load quotation requests.")));if(id&&canCreate)void Promise.all([suppliersApi.lookup(companyId),inventoryItemsApi.list(companyId)]).then(([s,i])=>{if(active){setSuppliers(s);setItems(i);}}).catch(e=>active&&setError(apiError(e,"Unable to load supplier and item choices.")));return()=>{active=false;};},[companyId,id,canCreate]);
  useEffect(()=>{let active=true;if(!selectedId){setSelected(null);setChecked([]);return;}void getPurchaseRequisition(companyId,selectedId).then(r=>{if(active){setSelected(r);setChecked(r.lines.filter(l=>(l.outstandingToOrder??0)>0).map(l=>l.id));}}).catch(e=>active&&setError(apiError(e,"Unable to load approved lines.")));return()=>{active=false;};},[companyId,selectedId]);
  async function create(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");try{const result=await http.post<{id:string}>(root,{clientRequestId:createKey.current,requisitionId:selectedId,lineIds:checked,responseDue,currencyCode:currency});navigate(`${root}/${result.data.id}`);}catch(e){setError(apiError(e,"Unable to create quotation request."));}finally{setBusy(false);}}
  async function saveOffer(e:FormEvent){e.preventDefault();if(!row||busy)return;setBusy(true);setError("");try{await http.post(`${root}/${row.id}/offers`,{...offer,version:row.version,clientRequestId:quoteKey.current,lines:offerLines.filter(l=>l.include).map(({include:_,...l})=>l)});quoteKey.current=crypto.randomUUID();await load();setOffer(f=>({...f,supplierId:"",supplierReference:""}));}catch(e){setError(apiError(e,"Unable to save supplier quotation."));}finally{setBusy(false);}}
  async function saveAward(){if(!row||busy)return;setBusy(true);setError("");try{const lines=Object.entries(award).filter(([,quantity])=>quantity>0).map(([key,quantity])=>{const [quoteId,requisitionLineId]=key.split(":");return{quoteId,requisitionLineId,quantity};});await http.post(`${root}/${row.id}/award`,{clientRequestId:awardKey.current,version:row.version,justification,lines});await load();}catch(e){setError(apiError(e,"Unable to record supplier selection."));}finally{setBusy(false);}}
  const editLine=(index:number,change:Partial<OfferInput>)=>setOfferLines(lines=>lines.map((l,i)=>i===index?{...l,...change}:l));
  return <div className="prq-page"><PageHeader title={row?row.reference:tx("Supplier quotations")} subtitle={tx("Compare complete quoted costs and preserve the supplier-selection decision.")}/>{error&&<p role="alert" className="prq-alert">{tx(error)}</p>}
    {!id&&<><section className="prq-panel"><h2>{tx("Quotation requests")}</h2>{requests.length===0?<p>{tx("No quotation requests yet.")}</p>:<ul>{requests.map(r=><li key={r.id}><Link to={`${root}/${r.id}`}>{r.reference}</Link> · {tx(r.status)} · {tx("Response due")} {r.responseDue}</li>)}</ul>}</section>
    {canCreate&&<form className="prq-panel" onSubmit={e=>void create(e)}><h2>{tx("Request quotations from approved requirements")}</h2><div className="prq-form-grid"><label>{tx("Requisition")}<Select required value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">{tx("Choose approved requisition")}</option>{requisitions.map(r=><option key={r.id} value={r.id}>{r.requisitionNo} · {r.businessJustification}</option>)}</Select></label><label>{tx("Responses due")}<Input required type="date" value={responseDue} onChange={e=>setResponseDue(e.target.value)}/></label><label>{tx("Comparison currency")}<Input required minLength={3} maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label></div>{selected?.lines.filter(l=>(l.outstandingToOrder??0)>0).map(l=><label key={l.id} style={{display:"block"}}><Checkbox checked={checked.includes(l.id)} onChange={e=>setChecked(c=>e.target.checked?[...c,l.id]:c.filter(x=>x!==l.id))}/>{l.itemName} · {qty(l.outstandingToOrder)} {l.uomName}</label>)}<Button type="submit" disabled={busy||!checked.length}>{tx("Create quotation request")}</Button></form>}</>}
    {row&&<><Link to={root}>{tx("All quotation requests")}</Link><section className="prq-panel"><h2>{tx("Requested items")}</h2><p>{tx(row.status)} · {tx("Comparison currency")}: {row.currencyCode}</p><ul>{row.requirements.map(l=><li key={l.requisitionLineId}><Link to={`/companies/${companyId}/procurement/requisitions/${l.requisitionId}`}>{l.requisitionNo}</Link> · {l.itemName}: {qty(l.quantity)} {l.unit} ({qty(l.quantity*l.toBaseFactor)} {tx("base units")}){l.specification?` · ${l.specification}`:""}</li>)}</ul></section>
      <section className="prq-panel"><h2>{tx("Compare offers and select suppliers")}</h2><p>{tx("Costs include quoted discounts, taxes and allocated freight, converted to the comparison currency per base unit. Award quantities use the requested unit.")}</p>
        {row.requirements.map(req=><div key={req.requisitionLineId}><h3>{req.itemName} · {qty(req.quantity)} {req.unit}</h3><div className="prq-table-wrap"><table className="prq-table"><thead><tr>{["Supplier","Quoted quantity","Total cost","Cost per base unit","Delivery","Valid until","Award quantity"].map(h=><th key={h}>{tx(h)}</th>)}</tr></thead><tbody>{row.quotes.filter(q=>q.isCurrent).flatMap(q=>q.lines.filter(l=>l.requisitionLineId===req.requisitionLineId).map(l=><tr key={q.id}><td>{q.supplierName}<br/>{q.supplierReference}</td><td>{qty(l.quantity)} {l.unit}<br/>{qty(l.baseQuantity)} {tx("base units")}</td><td>{money(l.total,row.currencyCode)}</td><td>{money(l.costPerBaseUnit,row.currencyCode)}</td><td>{q.deliveryDate}<br/>{q.paymentTermDays} {tx("days payment terms")}</td><td>{q.validUntil}</td><td>{canCreate&&row.status==="Open"?<Input aria-label={`${tx("Award quantity")} ${req.itemName} ${q.supplierName}`} type="number" min={0} max={req.quantity} step="0.0001" value={award[`${q.id}:${req.requisitionLineId}`]??0} onChange={e=>setAward(a=>({...a,[`${q.id}:${req.requisitionLineId}`]:Number(e.target.value)}))}/>:"—"}</td></tr>))}</tbody></table></div></div>)}
        {canCreate&&row.status==="Open"&&<><label>{tx("Supplier-selection justification")}<Textarea maxLength={2000} value={justification} onChange={e=>setJustification(e.target.value)}/></label><p>{tx("Explain higher-cost selections or quotation-count exceptions. Blocking rules require additional valid quotations.")}</p><Button disabled={busy||!Object.values(award).some(q=>q>0)} onClick={()=>void saveAward()}>{tx("Record supplier selection")}</Button></>}
        {row.awards.length>0&&canCreate&&<label>{tx("Company currency per comparison currency unit")}<Input type="number" min="0.00000001" step="0.00000001" value={comparisonExchangeRate} onChange={e=>setComparisonExchangeRate(Number(e.target.value))}/></label>}{createdOrders.map(p=><p key={p.id}><Link to={`/procurement/purchase-orders/${p.id}`}>{p.poNo}</Link> · {tx("Draft order awaiting normal approval")}</p>)}
        {row.awards.map(a=><article key={a.id}><h3>{tx("Saved supplier selection")}</h3><p>{a.justification}</p><ul>{a.lines.map((l,i)=><li key={i}>{row.quotes.find(q=>q.id===l.quoteId)?.supplierName} · {row.requirements.find(r=>r.requisitionLineId===l.requisitionLineId)?.itemName} · {qty(l.quantity)} · {money(l.comparisonAmount,row.currencyCode)}</li>)}</ul>{canCreate&&<Button disabled={busy} onClick={()=>void createOrders(a.id)}>{tx("Create or reopen draft purchase orders")}</Button>}</article>)}
      </section>
      {canCreate&&row.status==="Open"&&<form className="prq-panel" onSubmit={e=>void saveOffer(e)}><h2>{tx("Record supplier quotation")}</h2><p>{tx("A new quotation from the same supplier replaces their current offer while retaining the earlier version.")}</p><div className="prq-form-grid"><label>{tx("Approved supplier")}<Select required value={offer.supplierId} onChange={e=>setOffer(o=>({...o,supplierId:e.target.value}))}><option value="">{tx("Choose supplier")}</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></label><label>{tx("Supplier quote reference")}<Input required maxLength={120} value={offer.supplierReference} onChange={e=>setOffer(o=>({...o,supplierReference:e.target.value}))}/></label><label>{tx("Quote currency")}<Input required maxLength={3} value={offer.currencyCode} onChange={e=>setOffer(o=>({...o,currencyCode:e.target.value.toUpperCase()}))}/></label><label>{tx("Comparison currency per quote currency unit")}<Input required type="number" min={0.00000001} step="0.00000001" value={offer.exchangeRate} onChange={e=>setOffer(o=>({...o,exchangeRate:Number(e.target.value)}))}/></label><label>{tx("Valid until")}<Input type="date" required value={offer.validUntil} onChange={e=>setOffer(o=>({...o,validUntil:e.target.value}))}/></label><label>{tx("Delivery date")}<Input type="date" required value={offer.deliveryDate} onChange={e=>setOffer(o=>({...o,deliveryDate:e.target.value}))}/></label><label>{tx("Payment terms (days)")}<Input type="number" min={0} max={365} required value={offer.paymentTermDays} onChange={e=>setOffer(o=>({...o,paymentTermDays:Number(e.target.value)}))}/></label></div>
        {offerLines.map((line,index)=>{const req=row.requirements.find(r=>r.requisitionLineId===line.requisitionLineId)!;const item=items.find(i=>i.id===req.itemId);const units=(item?.uoms??item?.allowedUoms??[]).filter(u=>u.isActive&&u.isPurchase);return <fieldset key={line.requisitionLineId}><legend><Checkbox checked={line.include} onChange={e=>editLine(index,{include:e.target.checked})}/>{req.itemName}</legend><div className="prq-form-grid"><label>{tx("Quoted unit")}<Select disabled={!req.itemId||!line.include} value={line.uomId??""} onChange={e=>editLine(index,{uomId:e.target.value})}><option value={req.uomId??""}>{req.unit}</option>{units.filter(u=>u.uomId!==req.uomId).map(u=><option key={u.uomId} value={u.uomId}>{u.code}</option>)}</Select></label>{(["quantity","unitPrice","discountPercent","taxRatePercent","freight"] as const).map((key,i)=><label key={key}>{tx(["Quoted quantity","Unit price","Discount %","Tax %","Allocated freight"][i])}<Input type="number" disabled={!line.include} required={line.include} min={key==="quantity"?0.0001:0} max={key.endsWith("Percent")?100:undefined} step="0.0001" value={line[key]} onChange={e=>editLine(index,{[key]:Number(e.target.value)})}/></label>)}</div>{line.include&&<NegotiatedPriceHint companyId={companyId} supplierId={offer.supplierId} branchId={row.branchId} itemId={req.itemId} uomId={line.uomId} quantity={line.quantity} currency={offer.currencyCode} date={todayIso()} onUse={price=>editLine(index,{unitPrice:price,discountPercent:0})}/>}</fieldset>;})}
        <label>{tx("Quotation notes")}<Textarea maxLength={1000} value={offer.notes} onChange={e=>setOffer(o=>({...o,notes:e.target.value}))}/></label><Button disabled={busy||!offerLines.some(l=>l.include)} type="submit">{tx("Save supplier quotation")}</Button></form>}
      <section className="prq-panel"><h2>{tx("Earlier quotations")}</h2>{row.quotes.filter(q=>!q.isCurrent).map(q=><details key={q.id}><summary>{q.supplierName} · {q.supplierReference}</summary><p>{q.notes}</p><ul>{q.lines.map(l=><li key={l.requisitionLineId}>{row.requirements.find(r=>r.requisitionLineId===l.requisitionLineId)?.itemName}: {qty(l.quantity)} {l.unit} · {money(l.total,row.currencyCode)}</li>)}</ul></details>)}</section>
    </>}
  </div>;
}
