import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {http} from "../../../api/http";
import {PageHeader} from "../../../components/PageHeader";
import {Button} from "../../../components/ui/button";
import {Input} from "../../../components/ui/input";
import {Select} from "../../../components/ui/select";
import {Textarea} from "../../../components/ui/textarea";
import {useI18n} from "../../../i18n";
import {useHasPermission} from "../../../auth/usePermissions";
import {stockLocationsApi} from "../../inventory/stock-locations/api/stockLocationsApi";
import type {StockLocationDto} from "../../inventory/stock-locations/types";
import {suppliersApi,type SupplierLookup} from "../api/purchasingApi";
import {asItems,apiError,qty,todayIso,useCompanyId} from "../components/p2pShared";
type Requirement={requisitionId:string;requisitionNo:string;branchId:string;suggestedSupplierId?:string;locationId?:string;requiredByDateUtc:string;lineId:string;itemName:string;uomName:string;quantity:number;estimatedUnitPrice:number};
export default function ProcurementConsolidationPage(){
 const {tx}=useI18n(),companyId=useCompanyId(),canCreate=useHasPermission("purchasing.create");
 const [rows,setRows]=useState<Requirement[]>([]),[suppliers,setSuppliers]=useState<SupplierLookup[]>([]),[locations,setLocations]=useState<StockLocationDto[]>([]),[branches,setBranches]=useState<{id:string;name:string}[]>([]),[selected,setSelected]=useState<Record<string,{quantity:string;price:string}>>({}),[supplierId,setSupplier]=useState(""),[mode,setMode]=useState("Direct"),[locationId,setLocation]=useState(""),[date,setDate]=useState(todayIso()),[reason,setReason]=useState(""),[key,setKey]=useState(()=>crypto.randomUUID()),[orders,setOrders]=useState<{id:string;poNo:string}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const root=`/companies/${companyId}/procurement`;
 useEffect(()=>{if(!companyId)return;let active=true;Promise.all([http.get<Requirement[]>(`${root}/consolidation/requirements`),suppliersApi.lookup(companyId),stockLocationsApi.list(companyId),http.get<{id:string;name:string}[]>(`/companies/${companyId}/branches`).catch(()=>({data:[] as {id:string;name:string}[]}))]).then(([r,s,l,b])=>{if(active){setRows(r.data);setSuppliers(s);setLocations(l);setBranches(asItems(b.data));}}).catch(e=>{if(active)setError(apiError(e,"Unable to load branch requirements."));});return()=>{active=false;};},[companyId]);
 useEffect(()=>{setKey(crypto.randomUUID());setOrders([]);},[selected,supplierId,mode,locationId,date,reason]);
 async function create(){if(busy)return;setBusy(true);setError("");try{const r=await http.post<{id:string;poNo:string}[]>(`${root}/consolidation`,{clientRequestId:key,supplierId,mode,centralBranchId:mode==="Central"?locations.find(l=>l.id===locationId)?.branchId:null,centralLocationId:mode==="Central"?locationId:null,expectedDate:date,reason,lines:Object.entries(selected).map(([requisitionLineId,l])=>({requisitionLineId,quantity:Number(l.quantity),unitPrice:l.price===""?null:Number(l.price)}))});setOrders(r.data);}catch(e){setError(apiError(e,"Unable to finish consolidation. Retry unchanged selections to recover any orders already created."));}finally{setBusy(false);}}
 return <main className="prq-page"><PageHeader title={tx("Branch purchasing consolidation")} subtitle={tx("Combine compatible requirements due within seven days. Source branch quantities stay attached to every order line.")}/>{error&&<p role="alert">{tx(error)}</p>}<fieldset className="prq-panel" disabled={busy||orders.length>0}><legend>{tx("Supplier and delivery")}</legend><label>{tx("Supplier")}<Select value={supplierId} onChange={e=>setSupplier(e.target.value)}><option value="">{tx("Select supplier")}</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></label><label>{tx("Delivery mode")}<Select value={mode} onChange={e=>setMode(e.target.value)}><option value="Direct">{tx("Direct delivery: one order per branch destination")}</option><option value="Central">{tx("Central receipt followed by branch transfers")}</option></Select></label>{mode==="Central"&&<label>{tx("Central receiving warehouse")}<Select value={locationId} onChange={e=>setLocation(e.target.value)}><option value="">{tx("Select location")}</option>{locations.filter(l=>l.branchId).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</Select></label>}<label>{tx("Expected delivery date")}<Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></fieldset>
 <section className="prq-panel"><h2>{tx("Approved requirements")}</h2>{[...rows].sort((a,b)=>a.itemName.localeCompare(b.itemName)||a.requiredByDateUtc.localeCompare(b.requiredByDateUtc)).map(r=><fieldset disabled={busy||orders.length>0} key={r.lineId}><legend><label><Input type="checkbox" checked={!!selected[r.lineId]} onChange={e=>setSelected(s=>{const next={...s};if(e.target.checked)next[r.lineId]={quantity:String(r.quantity),price:String(r.estimatedUnitPrice)};else delete next[r.lineId];return next;})}/>{r.itemName} · {branches.find(b=>b.id===r.branchId)?.name}</label></legend><p><Link to={`/procurement/requisitions/${r.requisitionId}`}>{r.requisitionNo}</Link> · {qty(r.quantity)} {r.uomName} · {tx("Required")}: {r.requiredByDateUtc.slice(0,10)} · {suppliers.find(s=>s.id===r.suggestedSupplierId)?.name}</p>{selected[r.lineId]&&<div className="prq-form-grid"><label>{tx("Purchase quantity")}<Input type="number" min="0.0001" max={r.quantity} step="0.0001" value={selected[r.lineId].quantity} onChange={e=>setSelected({...selected,[r.lineId]:{...selected[r.lineId],quantity:e.target.value}})}/></label><label>{tx("Negotiated unit price")}<Input type="number" min={0} step="0.0001" value={selected[r.lineId].price} onChange={e=>setSelected({...selected,[r.lineId]:{...selected[r.lineId],price:e.target.value}})}/></label></div>}</fieldset>)}</section>
 <section className="prq-panel"><label>{tx("Consolidation reason")}<Textarea disabled={busy||orders.length>0} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{orders.length?orders.map(o=><p key={o.id}><Link to={`/procurement/purchase-orders/${o.id}`}>{o.poNo}</Link> · {tx("Draft created; normal approvals apply")}</p>):canCreate&&<Button disabled={busy||!supplierId||!Object.keys(selected).length||!reason.trim()||(mode==="Central"&&!locationId)} onClick={()=>void create()}>{tx("Create consolidated draft orders")}</Button>}</section></main>;
}
