import {useEffect,useState} from "react";
import {Link,useNavigate} from "react-router-dom";
import {http} from "../../../api/http";
import {PageHeader} from "../../../components/PageHeader";
import {Button} from "../../../components/ui/button";
import {Input} from "../../../components/ui/input";
import {Select} from "../../../components/ui/select";
import {Textarea} from "../../../components/ui/textarea";
import {useI18n} from "../../../i18n";
import {useHasPermission} from "../../../auth/usePermissions";
import {inventoryItemsApi} from "../../inventoryMaster/items/api/inventoryItemsApi";
import type {InventoryItemDto} from "../../inventoryMaster/items/types";
import {stockLocationsApi} from "../../inventory/stock-locations/api/stockLocationsApi";
import type {StockLocationDto} from "../../inventory/stock-locations/types";
import {suppliersApi,type SupplierLookup} from "../api/purchasingApi";
import {apiError,qty,useCompanyId} from "../components/p2pShared";
import ProductionDemandPanel from "../components/ProductionDemandPanel";
type Preview={fingerprint:string;requiredDate:string;dailyConsumption:number;targetStock:number;leadTimeDays:number;suggestedQuantity:number;existingRequisitionId?:string;assumptions:string[];availability:{baseUnit:string;availableBaseQuantity:number;incomingByRequiredDate:number;explanations:string[];requisitions:{id:string;reference:string;quantity:number;unit:string}[]}};
export default function ProcurementPlanningPage(){
 const {tx}=useI18n(),companyId=useCompanyId(),navigate=useNavigate(),canCreate=useHasPermission("purchasing.create");
 const [items,setItems]=useState<InventoryItemDto[]>([]),[locations,setLocations]=useState<StockLocationDto[]>([]),[suppliers,setSuppliers]=useState<SupplierLookup[]>([]),[locationId,setLocation]=useState(""),[itemId,setItem]=useState(""),[supplierId,setSupplier]=useState(""),[lookbackDays,setLookback]=useState(90),[coverageDays,setCoverage]=useState(7),[minimumStock,setMinimum]=useState(0),[safetyStock,setSafety]=useState(0),[shelfLife,setShelfLife]=useState(""),[preview,setPreview]=useState<Preview|null>(null),[reviewedQuantity,setQuantity]=useState(""),[price,setPrice]=useState("0"),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const planning={branchId:locations.find(l=>l.id===locationId)?.branchId,locationId,itemId,supplierId:supplierId||null,lookbackDays,coverageDays,minimumStock,safetyStock,shelfLifeDays:shelfLife?Number(shelfLife):null};
 useEffect(()=>{if(!companyId)return;let active=true;Promise.all([inventoryItemsApi.list(companyId),stockLocationsApi.list(companyId),suppliersApi.lookup(companyId)]).then(([i,l,s])=>{if(active){setItems(i);setLocations(l);setSuppliers(s);}}).catch(e=>{if(active)setError(apiError(e,"Unable to load planning options."));});return()=>{active=false;};},[companyId]);
 useEffect(()=>setPreview(null),[companyId,locationId,itemId,supplierId,lookbackDays,coverageDays,minimumStock,safetyStock,shelfLife]);
 async function calculate(){if(busy)return;setBusy(true);setError("");try{const r=await http.post<Preview>(`/companies/${companyId}/procurement/planning/replenishment/preview`,planning);setPreview(r.data);setQuantity(String(r.data.suggestedQuantity));}catch(e){setError(apiError(e,"Unable to calculate replenishment."));}finally{setBusy(false);}}
 async function create(){if(!preview||busy)return;setBusy(true);setError("");try{const r=await http.post(`/companies/${companyId}/procurement/planning/replenishment/requisition`,{planning,fingerprint:preview.fingerprint,reviewedQuantity:Number(reviewedQuantity),estimatedUnitPrice:Number(price),reason});navigate(`/procurement/requisitions/${r.data.id}`);}catch(e){setError(apiError(e,"Unable to create the requisition. Refresh the recommendation if stock changed."));}finally{setBusy(false);}}
 return <main className="prq-page"><PageHeader title={tx("Purchasing planning")} subtitle={tx("Review stock, consumption and incoming orders before requesting replenishment.")}/>{error&&<p role="alert">{tx(error)}</p>}<fieldset className="prq-panel" disabled={busy}><legend>{tx("Replenishment assumptions")}</legend><div className="prq-form-grid"><label>{tx("Destination")}<Select value={locationId} onChange={e=>setLocation(e.target.value)}><option value="">{tx("Select location")}</option>{locations.filter(l=>l.branchId).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</Select></label><label>{tx("Item")}<Select value={itemId} onChange={e=>{setItem(e.target.value);setMinimum(Number(items.find(i=>i.id===e.target.value)?.reorderLevel||0));}}><option value="">{tx("Select item")}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</Select></label><label>{tx("Supplier lead time")}<Select value={supplierId} onChange={e=>setSupplier(e.target.value)}><option value="">{tx("No supplier: zero-day assumption")}</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></label><label>{tx("Consumption lookback days")}<Input type="number" min={7} max={365} value={lookbackDays} onChange={e=>setLookback(Number(e.target.value))}/></label><label>{tx("Coverage days")}<Input type="number" min={1} max={365} value={coverageDays} onChange={e=>setCoverage(Number(e.target.value))}/></label><label>{tx("Minimum base quantity")}<Input type="number" min={0} value={minimumStock} onChange={e=>setMinimum(Number(e.target.value))}/></label><label>{tx("Safety stock in base units")}<Input type="number" min={0} value={safetyStock} onChange={e=>setSafety(Number(e.target.value))}/></label><label>{tx("Shelf life in days, if applicable")}<Input type="number" min={1} value={shelfLife} onChange={e=>setShelfLife(e.target.value)}/></label></div><Button disabled={!locationId||!itemId} onClick={()=>void calculate()}>{tx("Calculate recommendation")}</Button></fieldset>
 {preview&&<section className="prq-panel"><h2>{tx("Suggested purchase")}: {qty(preview.suggestedQuantity)} {preview.availability.baseUnit}</h2><p>{tx("Required date")}: {preview.requiredDate} · {tx("Daily consumption")}: {qty(preview.dailyConsumption)} · {tx("Target stock")}: {qty(preview.targetStock)}</p><p>{tx("Usable stock")}: {qty(preview.availability.availableBaseQuantity)} · {tx("Incoming by required date")}: {qty(preview.availability.incomingByRequiredDate)}</p><ul>{[...preview.assumptions,...preview.availability.explanations].map((a,i)=><li key={i}>{a}</li>)}</ul>{preview.availability.requisitions.map(r=><p key={r.id}><Link to={`/procurement/requisitions/${r.id}`}>{r.reference}</Link> · {qty(r.quantity)} {r.unit}</p>)}{preview.existingRequisitionId?<Link to={`/procurement/requisitions/${preview.existingRequisitionId}`}>{tx("Open today's existing replenishment request")}</Link>:canCreate&&<fieldset disabled={busy}><legend>{tx("Review and create draft")}</legend><label>{tx("Reviewed base quantity")}<Input type="number" min="0.0001" step="0.0001" value={reviewedQuantity} onChange={e=>setQuantity(e.target.value)}/></label><label>{tx("Estimated price per base unit")}<Input type="number" min={0} step="0.0001" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>{tx("Review reason and any quantity adjustment")}<Textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={Number(reviewedQuantity)<=0||!reason.trim()} onClick={()=>void create()}>{tx("Create draft requisition")}</Button></fieldset>}</section>}
 <ProductionDemandPanel companyId={companyId} locations={locations}/></main>;
}
