import {useEffect,useRef,useState} from "react";
import {Link} from "react-router-dom";
import {http} from "../../../api/http";
import {PageHeader} from "../../../components/PageHeader";
import {Button} from "../../../components/ui/button";
import {Input} from "../../../components/ui/input";
import {Select} from "../../../components/ui/select";
import {useI18n} from "../../../i18n";
import {suppliersApi,type SupplierLookup} from "../api/purchasingApi";
import {asItems,apiError,money,qty,todayIso,useCompanyId} from "../components/p2pShared";
type Dashboard={from:string;to:string;spend:number;supplierConcentrationPercent:number;onTimeDeliveryPercent?:number;deliverySample:number;emergencyCount:number;emergencyCommittedAmount:number;emergencyActualSpend:number;workCounts:{kind:string;count:number}[];work:{kind:string;id:string;reference:string;status:string;dueAtUtc?:string;amount?:number;link:string;detail:string}[];workCount:number;supplierSpend:{supplierId:string;name:string;amount:number;sharePercent:number;invoiceIds:string[]}[];periodNote:string};
export default function ProcurementDashboardPage(){
 const {tx}=useI18n(),companyId=useCompanyId();const [data,setData]=useState<Dashboard|null>(null),[branches,setBranches]=useState<{id:string;name:string}[]>([]),[suppliers,setSuppliers]=useState<SupplierLookup[]>([]),[filters,setFilters]=useState({from:todayIso(-90),to:todayIso(),branchId:"",supplierId:"",category:"",status:"",workType:""}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const generation=useRef(0);
 async function load(){if(!companyId)return;const run=++generation.current;setBusy(true);setError("");try{const response=(await http.get<Dashboard>(`/companies/${companyId}/procurement/dashboard`,{params:Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==""))})).data;if(run===generation.current)setData(response);}catch(e){if(run===generation.current){setData(null);setError(apiError(e,"Unable to load the procurement dashboard."));}}finally{if(run===generation.current)setBusy(false);}}
 useEffect(()=>{setData(null);void load();let active=true;Promise.all([http.get<{id:string;name:string}[]>(`/companies/${companyId}/branches`).catch(()=>({data:[] as {id:string;name:string}[]})),suppliersApi.lookup(companyId)]).then(([b,s])=>{if(active){setBranches(asItems(b.data));setSuppliers(s);}}).catch(e=>{if(active)setError(apiError(e,"Unable to load report filters."));});return()=>{active=false;++generation.current;};},[companyId]);
 return <main className="prq-page"><PageHeader title={tx("Purchasing overview")} subtitle={tx("Approvals, delivery exceptions, invoices, returns, budgets and emergency reviews in your authorized scope.")}/>{error&&<p role="alert">{tx(error)}</p>}<form className="prq-panel" onSubmit={e=>{e.preventDefault();void load();}}><fieldset disabled={busy}><legend>{tx("Report filters")}</legend><div className="prq-form-grid">{(["from","to"] as const).map(k=><label key={k}>{tx(k==="from"?"From":"To")}<Input required type="date" value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}/></label>)}<label>{tx("Branch")}<Select value={filters.branchId} onChange={e=>setFilters({...filters,branchId:e.target.value})}><option value="">{tx("All authorized branches")}</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select></label><label>{tx("Supplier")}<Select value={filters.supplierId} onChange={e=>setFilters({...filters,supplierId:e.target.value})}><option value="">{tx("All suppliers")}</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></label><label>{tx("Category")}<Input value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}/></label><label>{tx("Document status")}<Select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">{tx("All statuses")}</option>{["Draft","Submitted","PendingApproval","PendingFnbApproval","PendingFinanceApproval","Approved","Sent","PartiallyReceived","Received","Closed","OnHold","Matched","Posted"].map(s=><option key={s}>{s}</option>)}</Select></label><label>{tx("Work requiring attention")}<Select value={filters.workType} onChange={e=>setFilters({...filters,workType:e.target.value})}><option value="">{tx("All work")}</option>{["Pending approval","Overdue order","Partial delivery","Price exception","Invoice exception","Unresolved return","Budget overrun","Emergency review"].map(s=><option key={s}>{s}</option>)}</Select></label></div><Button type="submit">{tx(busy?"Loading...":"Apply filters")}</Button></fieldset></form>
 {data&&<><section className="prq-panel"><h2>{data.from} – {data.to}</h2><p>{data.periodNote}</p><div className="prq-form-grid"><div><h3>{tx("Approved invoice spend")}</h3><strong>{money(data.spend)}</strong></div><div><h3>{tx("Largest supplier share")}</h3><strong>{qty(data.supplierConcentrationPercent)}%</strong></div><div><h3>{tx("On-time deliveries")}</h3><strong>{data.onTimeDeliveryPercent==null?tx("Insufficient data"):`${qty(data.onTimeDeliveryPercent)}%`}</strong><p>{data.deliverySample} {tx("receipts with a promised date")}</p></div><div><h3>{tx("Emergency purchases")}</h3><strong>{data.emergencyCount}</strong><p>{tx("Actual spend")}: {money(data.emergencyActualSpend)} · {tx("Authorized commitment")}: {money(data.emergencyCommittedAmount)}</p></div></div></section><section className="prq-panel"><h2>{tx("Work queue")}</h2><p>{data.workCounts.map(c=>`${tx(c.kind)}: ${c.count}`).join(" · ")}</p>{!data.workCount&&<p>{tx("No work matches these filters.")}</p>}{data.workCount>data.work.length&&<p>{tx("Showing the first 200 results. Narrow the filters to inspect the remaining work.")}</p>}{data.work.map(w=><article key={`${w.kind}:${w.id}`}><h3><Link to={w.link}>{w.reference}</Link> · {tx(w.kind)}</h3><p>{tx(w.status)}{w.dueAtUtc?` · ${tx("Due")}: ${w.dueAtUtc.slice(0,10)}`:""}{w.amount!=null?` · ${money(w.amount)}`:""}</p><p>{w.detail}</p></article>)}</section><section className="prq-panel"><h2>{tx("Supplier spend and concentration")}</h2>{data.supplierSpend.map(s=><details key={s.supplierId}><summary>{s.name} · {money(s.amount)} · {qty(s.sharePercent)}%</summary><p>{s.invoiceIds.map((id,i)=><span key={id}><Link to={`/procurement/supplier-invoices/${id}`}>{tx("Invoice")} {i+1}</Link> </span>)}</p></details>)}<Link to="/procurement/supplier-performance">{tx("Open delivery and quality performance")}</Link></section></>}
 </main>;
}
