import { useEffect,useState,type FormEvent } from "react";
import { PageHeader } from "../../../components/PageHeader";
import { Button } from "../../../components/ui/button";
import { Input } from "../../../components/ui/input";
import { Select } from "../../../components/ui/select";
import { Checkbox } from "../../../components/ui/checkbox";
import { useI18n } from "../../../i18n";
import { http } from "../../../api/http";
import {inventoryItemsApi} from "../../inventoryMaster/items/api/inventoryItemsApi";
import { approvalsApi,type ProcurementRule,type RuleVersion } from "../api/procurementApprovalsApi";
import {asItems, apiError,dateTime,useCompanyId } from "../components/p2pShared";
import "./procurement.css";

const fresh=():ProcurementRule=>({name:"",kind:"Approval",precedence:100,action:"Review",preventSelfApproval:true,stages:[{name:"Purchasing approval",approverIds:[],dueHours:24,escalationUserIds:[]}],lookbackDays:90,thresholdMode:"Either",minimumQuotations:1,notifyUserIds:[],allowedSupplierStatuses:["Approved"],requireSupplierItem:false});
export default function ProcurementRulesPage(){
  const {tx}=useI18n(),companyId=useCompanyId();
  const [rules,setRules]=useState<RuleVersion[]>([]),[users,setUsers]=useState<{id:string;name:string}[]>([]),[branches,setBranches]=useState<{id:string;name:string}[]>([]);
  const [items,setItems]=useState<{id:string;name:string}[]>([]),[draftResult,setDraftResult]=useState<{matches:boolean;triggered:boolean;action:string}|null>(null);
  const [rule,setRule]=useState<ProcurementRule>(fresh),[editing,setEditing]=useState<RuleVersion|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [sample,setSample]=useState({branchId:"",category:"",priority:"Normal",amount:0,budgetStatus:"Unknown",itemId:"",increasePercent:20,additionalCost:1000}),[preview,setPreview]=useState<{definition:ProcurementRule;revision:number}[]|null>(null);
  async function load(){const [r,u,b]=await Promise.all([approvalsApi.rules(companyId),approvalsApi.users(companyId),http.get<{id:string;name:string}[]>(`/companies/${companyId}/branches`)]);setRules(r);setUsers(u);setBranches(asItems(b.data));}
  useEffect(()=>{if(companyId)void load().catch(e=>setError(apiError(e,"Unable to load approval rules.")));},[companyId]);
  useEffect(()=>{if(companyId)void inventoryItemsApi.list(companyId).then(rows=>setItems(rows.filter(x=>x.isActive!==false))).catch(e=>setError(apiError(e,"Unable to load rule items.")));},[companyId]);
  const set=<K extends keyof ProcurementRule>(key:K,value:ProcurementRule[K])=>setRule(r=>({...r,[key]:value}));
  async function save(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");setNotice("");try{await approvalsApi.save(companyId,rule,editing?.policyId,editing?.revision);await load();setEditing(null);setRule(fresh());setNotice("Approval rule saved. New submissions will use the matching rule; existing reviews retain their saved route.");}catch(e){setError(apiError(e,"Unable to save approval rule."));}finally{setBusy(false);}}
  async function test(){setError("");try{setPreview(await approvalsApi.preview(companyId,{...sample,branchId:sample.branchId||undefined,itemId:sample.itemId||undefined}));}catch(e){setError(apiError(e,"Unable to preview matching rules."));}}
  async function previewDraft(){setError("");try{setDraftResult((await http.post<{matches:boolean;triggered:boolean;action:string}>(`/companies/${companyId}/procurement/rules/preview-draft`,{definition:rule,facts:{...sample,branchId:sample.branchId||null,itemId:sample.itemId||null}})).data);}catch(e){setError(apiError(e,"Unable to preview the draft rule."));}}
  return <div className="prq-page"><PageHeader title={tx("Purchasing rules")} subtitle={tx("Configure approval, price and quotation controls, then preview their effect before saving.")}/>
    {error&&<p role="alert" className="prq-alert">{tx(error)}</p>}{notice&&<p role="status">{tx(notice)}</p>}
    <section className="prq-panel"><h2>{tx("Current rules")}</h2><p>{tx("Lower precedence numbers are checked first. At equal precedence, the most specific matching rule wins. Revisions preserve earlier approval routes.")}</p>
      {rules.filter(r=>r.isActive).length===0&&<p>{tx("No configured rules. The existing F&B and finance approval workflow applies.")}</p>}
      {rules.filter(r=>r.isActive).map(r=><div key={r.id}><Button variant="ghost" onClick={()=>{setEditing(r);setRule(structuredClone(r.definition));setNotice("");}}>{r.definition.name}</Button> · {tx("Revision")} {r.revision} · {tx("Precedence")} {r.definition.precedence}</div>)}
      <details><summary>{tx("Rule history")}</summary>{rules.map(r=><p key={r.id}>{r.definition.name} · {tx("Revision")} {r.revision} · {dateTime(r.createdAtUtc)} · {tx(r.isActive?"Current":"Superseded")}</p>)}</details>
    </section>
    <form className="prq-panel" onSubmit={e=>void save(e)}><h2>{tx(editing?"Revise approval rule":"New approval rule")}</h2>
      <div className="prq-form-grid"><label>{tx("Rule type")}<Select value={rule.kind} onChange={e=>setRule(r=>({...r,kind:e.target.value,stages:["Quotations","Budget","SupplierEligibility"].includes(e.target.value)?[]:r.stages.length?r.stages:fresh().stages}))}>{["Approval","Price","Quotations","Budget","SupplierEligibility","Emergency"].map(k=><option key={k} value={k}>{tx(k)}</option>)}</Select></label>
      <label>{tx("Item (blank for all)")}<Select value={rule.itemId??""} onChange={e=>set("itemId",e.target.value||undefined)}><option value="">{tx("All items")}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</Select></label>
      {rule.kind!=="Approval"&&<label>{tx("Action")}<Select value={rule.action} onChange={e=>set("action",e.target.value)}>{["Warn","Review","Block"].map(k=><option key={k} value={k}>{tx(k)}</option>)}</Select></label>}
      {rule.kind==="Price"&&<><label>{tx("Lookback days")}<Input type="number" min={1} max={730} value={rule.lookbackDays} onChange={e=>set("lookbackDays",Number(e.target.value))}/></label><label>{tx("Price increase threshold (%)")}<Input type="number" min={0} value={rule.priceIncreasePercent??""} onChange={e=>set("priceIncreasePercent",e.target.value===""?undefined:Number(e.target.value))}/></label><label>{tx("Additional cost threshold (base currency)")}<Input type="number" min={0} value={rule.costImpact??""} onChange={e=>set("costImpact",e.target.value===""?undefined:Number(e.target.value))}/></label><label>{tx("Threshold matching")}<Select value={rule.thresholdMode} onChange={e=>set("thresholdMode",e.target.value)}><option value="Either">{tx("Either threshold")}</option><option value="Both">{tx("Both thresholds")}</option></Select></label></>}
      {rule.kind==="SupplierEligibility"&&<><label>{tx("Allow legacy Active suppliers")}<Checkbox checked={(rule.allowedSupplierStatuses??["Approved"]).includes("Active")} onChange={e=>set("allowedSupplierStatuses",e.target.checked?["Approved","Active"]:["Approved"])}/></label><label>{tx("Require an active supplier-item record")}<Checkbox checked={rule.requireSupplierItem??false} onChange={e=>set("requireSupplierItem",e.target.checked)}/></label><p>{tx("Approved supplier status is always allowed. Suspended, inactive and pending-review suppliers remain blocked by supplier master controls. Review exceptions require independent finance approval; optional stage assignees restrict who may approve.")}</p></>}
      {rule.kind==="Budget"&&<p>{tx("For applicable budgets, this rule selects the overrun action. Mandatory review uses the designated budget owner and records the applied policy version.")}</p>}
      {rule.kind==="Quotations"&&<label>{tx("Minimum quotations")}<Input type="number" min={1} max={20} value={rule.minimumQuotations} onChange={e=>set("minimumQuotations",Number(e.target.value))}/></label>}
      <label>{tx("Notify recipients")}<Select multiple value={rule.notifyUserIds} onChange={e=>set("notifyUserIds",Array.from(e.target.selectedOptions,o=>o.value))}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</Select></label></div>
      <div className="prq-form-grid"><label>{tx("Rule name")}<Input required maxLength={160} value={rule.name} onChange={e=>set("name",e.target.value)}/></label>
      <label>{tx("Branch")}<Select value={rule.branchId??""} onChange={e=>set("branchId",e.target.value||undefined)}><option value="">{tx("All branches")}</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select></label>
      <label>{tx("Purchase category (blank for all)")}<Input maxLength={160} value={rule.category??""} onChange={e=>set("category",e.target.value||undefined)}/></label>
      <label>{tx("Priority")}<Select value={rule.priority??""} onChange={e=>set("priority",e.target.value||undefined)}><option value="">{tx("All priorities")}</option>{["Low","Normal","High","Urgent","Emergency"].map(p=><option key={p} value={p}>{tx(p)}</option>)}</Select></label>
      <label>{tx("Minimum amount")}<Input type="number" min={0} step="0.01" value={rule.minimumAmount??""} onChange={e=>set("minimumAmount",e.target.value===""?undefined:Number(e.target.value))}/></label>
      <label>{tx("Maximum amount")}<Input type="number" min={0} step="0.01" value={rule.maximumAmount??""} onChange={e=>set("maximumAmount",e.target.value===""?undefined:Number(e.target.value))}/></label>
      <label>{tx("Budget status")}<Select value={rule.budgetStatus??""} onChange={e=>set("budgetStatus",e.target.value||undefined)}><option value="">{tx("Any budget status")}</option>{["WithinBudget","OverBudget","Unbudgeted"].map(x=><option key={x} value={x}>{tx(x)}</option>)}</Select></label><label>{tx("Precedence")}<Input type="number" required value={rule.precedence} onChange={e=>set("precedence",Number(e.target.value))}/></label></div>
      <label><Checkbox checked={rule.preventSelfApproval} onChange={e=>set("preventSelfApproval",e.target.checked)}/>{tx("Prevent requester self-approval, including through delegates")}</label>
      {rule.stages.map((stage,index)=><fieldset key={index}><legend>{tx("Approval stage")} {index+1}</legend><div className="prq-form-grid">
        <label>{tx("Stage name")}<Input required maxLength={100} value={stage.name} onChange={e=>set("stages",rule.stages.map((s,i)=>i===index?{...s,name:e.target.value}:s))}/></label>
        <label>{tx("Reviewers (any one may decide)")}<Select multiple required value={stage.approverIds} onChange={e=>set("stages",rule.stages.map((s,i)=>i===index?{...s,approverIds:Array.from(e.target.selectedOptions,o=>o.value)}:s))}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</Select></label>
        <label>{tx("Due within hours")}<Input type="number" required min={1} max={720} value={stage.dueHours} onChange={e=>set("stages",rule.stages.map((s,i)=>i===index?{...s,dueHours:Number(e.target.value)}:s))}/></label>
        <label>{tx("Escalate overdue reviews to")}<Select multiple value={stage.escalationUserIds??[]} onChange={e=>set("stages",rule.stages.map((s,i)=>i===index?{...s,escalationUserIds:Array.from(e.target.selectedOptions,o=>o.value)}:s))}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</Select></label>
      </div><Button type="button" variant="ghost" disabled={rule.stages.length===1} onClick={()=>set("stages",rule.stages.filter((_,i)=>i!==index))}>{tx("Remove stage")}</Button></fieldset>)}
      <div className="prq-actions"><Button type="button" variant="secondary" disabled={rule.stages.length>=10} onClick={()=>set("stages",[...rule.stages,{name:"",approverIds:[],dueHours:24,escalationUserIds:[]}])}>{tx("Add stage")}</Button><Button type="submit" disabled={busy}>{tx(busy?"Saving...":"Save approval rule")}</Button>{editing&&<Button type="button" variant="ghost" onClick={()=>{setEditing(null);setRule(fresh());}}>{tx("Cancel editing")}</Button>}</div>
    </form>
    <section className="prq-panel"><h2>{tx("Test the draft before activation")}</h2><p>{tx("Use the sample company, branch, category, priority and amount below, plus these price facts. Testing does not activate the rule.")}</p><div className="prq-form-grid"><label>{tx("Sample item")}<Select value={sample.itemId} onChange={e=>setSample(s=>({...s,itemId:e.target.value}))}><option value="">{tx("No item")}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</Select></label><label>{tx("Sample increase (%)")}<Input type="number" value={sample.increasePercent} onChange={e=>setSample(s=>({...s,increasePercent:Number(e.target.value)}))}/></label><label>{tx("Sample additional cost")}<Input type="number" value={sample.additionalCost} onChange={e=>setSample(s=>({...s,additionalCost:Number(e.target.value)}))}/></label></div><Button variant="secondary" onClick={()=>void previewDraft()}>{tx("Test unsaved rule")}</Button>{draftResult&&<p>{tx(draftResult.triggered?"Rule triggers":draftResult.matches?"Scope matches; thresholds do not trigger":"Rule scope does not match")} · {tx(draftResult.action)}</p>}</section>
    <section className="prq-panel"><h2>{tx("Preview rule matching")}</h2><div className="prq-form-grid"><label>{tx("Branch")}<Select value={sample.branchId} onChange={e=>setSample(s=>({...s,branchId:e.target.value}))}><option value="">{tx("Company level")}</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select></label><label>{tx("Category")}<Input value={sample.category} onChange={e=>setSample(s=>({...s,category:e.target.value}))}/></label><label>{tx("Priority")}<Select value={sample.priority} onChange={e=>setSample(s=>({...s,priority:e.target.value}))}>{["Low","Normal","High","Urgent","Emergency"].map(p=><option key={p} value={p}>{tx(p)}</option>)}</Select></label><label>{tx("Estimated amount")}<Input type="number" min={0} value={sample.amount} onChange={e=>setSample(s=>({...s,amount:Number(e.target.value)}))}/></label></div><Button variant="secondary" onClick={()=>void test()}>{tx("Preview matching rules")}</Button>{preview&&<ol>{preview.length===0?<li>{tx("No matching configured rule. Standard approvals apply.")}</li>:preview.map((p,i)=><li key={i}>{p.definition.name} · {tx("Revision")} {p.revision}{i===0?` · ${tx("Selected approval rule")}`:""}</li>)}</ol>}</section>
  </div>;
}
