import {useEffect,useState} from "react";
import {http} from "../../../api/http";
import {PageHeader} from "../../../components/PageHeader";
import {Button} from "../../../components/ui/button";
import {Input} from "../../../components/ui/input";
import {Select} from "../../../components/ui/select";
import {Textarea} from "../../../components/ui/textarea";
import {useHasPermission} from "../../../auth/usePermissions";
import {useI18n} from "../../../i18n";
import {inventoryItemsApi} from "../../inventoryMaster/items/api/inventoryItemsApi";
import type {InventoryItemDto} from "../../inventoryMaster/items/types";
import {suppliersApi,type SupplierLookup} from "../api/purchasingApi";
import {asItems,apiError,qty,todayIso,useCompanyId} from "../components/p2pShared";
type Price={itemId:string;uomId:string;minimumQuantity:number;unitPrice:number};
type Agreement={id?:string;agreementId:string;revision?:number;expectedRevision:number;isCurrent?:boolean;supplierId:string;branchId?:string;name:string;from:string;to:string;currencyCode:string;paymentTermDays:number;terms:string;ownerId:string;expiryNoticeDays:number;prices:Price[]};
const fresh=():Agreement=>({agreementId:crypto.randomUUID(),expectedRevision:0,supplierId:"",name:"",from:todayIso(),to:`${new Date().getFullYear()}-12-31`,currencyCode:"ETB",paymentTermDays:30,terms:"",ownerId:"",expiryNoticeDays:30,prices:[{itemId:"",uomId:"",minimumQuantity:1,unitPrice:0}]});
export default function SupplierAgreementsPage(){
  const {tx}=useI18n(),companyId=useCompanyId(),canManage=useHasPermission("purchasing.manage");
  const [rows,setRows]=useState<Agreement[]>([]),[form,setForm]=useState<Agreement>(fresh),[suppliers,setSuppliers]=useState<SupplierLookup[]>([]),[items,setItems]=useState<InventoryItemDto[]>([]),[users,setUsers]=useState<{id:string;name:string}[]>([]),[branches,setBranches]=useState<{id:string;name:string}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const root=`/companies/${companyId}/procurement/agreements`;
  async function load(){setRows((await http.get<Agreement[]>(root)).data);}
  useEffect(()=>{if(!companyId)return;void load().catch(e=>setError(apiError(e,"Unable to load supplier agreements.")));void Promise.all([suppliersApi.lookup(companyId),inventoryItemsApi.list(companyId),http.get<{id:string;name:string}[]>(`/companies/${companyId}/branches`).catch(()=>({data:[] as {id:string;name:string}[]})),http.get<{id:string;name:string}[]>(`/companies/${companyId}/procurement/delegations/candidates`)]).then(([s,i,b,u])=>{setSuppliers(s);setItems(i);setBranches(asItems(b.data));setUsers(u.data);}).catch(e=>setError(apiError(e,"Unable to load agreement options.")));},[companyId]);
  async function save(){if(busy)return;setBusy(true);setError("");try{await http.post(root,{...form,branchId:form.branchId||null});await load();setForm(fresh());}catch(e){setError(apiError(e,"Unable to save supplier agreement."));}finally{setBusy(false);}}
  const patch=(index:number,value:Partial<Price>)=>setForm(f=>({...f,prices:f.prices.map((p,i)=>i===index?{...p,...value}:p)}));
  return <main className="prq-page"><PageHeader title={tx("Supplier agreements")} subtitle={tx("Versioned prices, minimum quantities, terms and expiry reminders.")}/>{error&&<p role="alert">{tx(error)}</p>}
    {rows.map(a=><details className="prq-panel" key={a.id}><summary>{a.name} · {tx("Revision")} {a.revision} · {a.from} – {a.to} · {tx(a.isCurrent?"Current":"Superseded")}</summary><p>{suppliers.find(s=>s.id===a.supplierId)?.name} · {a.currencyCode} · {a.paymentTermDays} {tx("payment-term days")}</p><p>{a.terms}</p><ul>{a.prices.map((p,i)=><li key={i}>{items.find(x=>x.id===p.itemId)?.name??tx("Item")} · {tx("Minimum quantity")}: {qty(p.minimumQuantity)} · {tx("Net unit price")}: {qty(p.unitPrice)}</li>)}</ul>{canManage&&a.isCurrent&&<Button variant="outline" onClick={()=>setForm({...a,expectedRevision:a.revision??0})}>{tx("Revise agreement")}</Button>}</details>)}
    {canManage&&<form className="prq-panel" onSubmit={e=>{e.preventDefault();void save();}}><h2>{tx("Agreement details")}</h2><div className="prq-form-grid"><label>{tx("Agreement name")}<Input required maxLength={160} value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></label><label>{tx("Supplier")}<Select required value={form.supplierId} onChange={e=>setForm(f=>({...f,supplierId:e.target.value}))}><option value="">{tx("Select supplier")}</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></label><label>{tx("Branch")}<Select value={form.branchId??""} onChange={e=>setForm(f=>({...f,branchId:e.target.value||undefined}))}><option value="">{tx("All branches")}</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select></label>{(["from","to"] as const).map(k=><label key={k}>{tx(k==="from"?"Valid from":"Valid until")}<Input required type="date" value={form[k]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></label>)}<label>{tx("Currency")}<Input required maxLength={3} value={form.currencyCode} onChange={e=>setForm(f=>({...f,currencyCode:e.target.value.toUpperCase()}))}/></label><label>{tx("Payment-term days")}<Input type="number" min={0} max={365} value={form.paymentTermDays} onChange={e=>setForm(f=>({...f,paymentTermDays:Number(e.target.value)}))}/></label><label>{tx("Agreement owner")}<Select required value={form.ownerId} onChange={e=>setForm(f=>({...f,ownerId:e.target.value}))}><option value="">{tx("Select owner")}</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</Select></label><label>{tx("Expiry notice days")}<Input type="number" min={1} max={180} value={form.expiryNoticeDays} onChange={e=>setForm(f=>({...f,expiryNoticeDays:Number(e.target.value)}))}/></label></div>
      {form.prices.map((p,index)=>{const item=items.find(i=>i.id===p.itemId);const units=(item?.uoms??item?.allowedUoms??[]).filter(u=>u.isPurchase||u.isBase);return <fieldset key={index}><legend>{tx("Item price break")} {index+1}</legend><div className="prq-form-grid"><label>{tx("Item")}<Select required value={p.itemId} onChange={e=>patch(index,{itemId:e.target.value,uomId:items.find(i=>i.id===e.target.value)?.baseUomId??""})}><option value="">{tx("Select item")}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</Select></label><label>{tx("Purchase unit")}<Select required value={p.uomId} onChange={e=>patch(index,{uomId:e.target.value})}>{units.map(u=><option key={u.uomId} value={u.uomId}>{u.code||u.name}</option>)}{item&&!units.some(u=>u.uomId===item.baseUomId)&&<option value={item.baseUomId}>{tx("Base unit")}</option>}</Select></label><label>{tx("Minimum purchase quantity")}<Input type="number" min="0.0001" step="0.0001" value={p.minimumQuantity} onChange={e=>patch(index,{minimumQuantity:Number(e.target.value)})}/></label><label>{tx("Negotiated net unit price")}<Input type="number" min={0} step="0.0001" value={p.unitPrice} onChange={e=>patch(index,{unitPrice:Number(e.target.value)})}/></label></div><Button type="button" variant="ghost" disabled={form.prices.length===1} onClick={()=>setForm(f=>({...f,prices:f.prices.filter((_,i)=>i!==index)}))}>{tx("Remove break")}</Button></fieldset>;})}
      <Button type="button" variant="secondary" onClick={()=>setForm(f=>({...f,prices:[...f.prices,{itemId:"",uomId:"",minimumQuantity:1,unitPrice:0}]}))}>{tx("Add item or quantity break")}</Button><label>{tx("Agreement terms")}<Textarea maxLength={4000} value={form.terms} onChange={e=>setForm(f=>({...f,terms:e.target.value}))}/></label><Button type="submit" disabled={busy}>{tx("Save agreement revision")}</Button>
    </form>}
  </main>;
}
