import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {http} from "../../../api/http";
import {PageHeader} from "../../../components/PageHeader";
import {Button} from "../../../components/ui/button";
import {Input} from "../../../components/ui/input";
import {Select} from "../../../components/ui/select";
import {Checkbox} from "../../../components/ui/checkbox";
import {useHasPermission} from "../../../auth/usePermissions";
import {useI18n} from "../../../i18n";
import {inventoryItemsApi} from "../../inventoryMaster/items/api/inventoryItemsApi";
import {asItems,apiError,money,qty,todayIso,useCompanyId} from "../components/p2pShared";
type Settings={enabled:boolean;deliveryWeight:number;qualityWeight:number;fulfilmentWeight:number;minimumDeliveries:number;version:string};
type Supplier={id:string;name:string;paymentTermDays:number;eligible:boolean;orders:number;deliveries:number;onTimePercent?:number;averageLeadDays?:number;averageLineFulfilmentPercent?:number;averageLineRejectionPercent?:number;averageLineReturnPercent?:number;score?:number;scoreStatus:string;alternativeExplanation:string;priceTrendNote:string;excludedPriceRecords:number;priceTrends:{itemId:string;itemName:string;month:string;baseUnit:string;baseQuantity:number;weightedUnitPrice:number;receipts:{grnId:string;grnNo:string}[]}[];transactions:{id:string;poNo:string;orderDate:string;receipts:{id:string;grnNo:string}[];returns:{id:string;returnNo:string}[]}[]};
type Report={from:string;to:string;scope:string;settings:Settings;suppliers:Supplier[]};
export default function SupplierPerformancePage(){
  const {tx}=useI18n(),companyId=useCompanyId(),canManage=useHasPermission("purchasing.manage");
  const [report,setReport]=useState<Report|null>(null),[settings,setSettings]=useState<Settings|null>(null),[items,setItems]=useState<{id:string;name:string}[]>([]),[branches,setBranches]=useState<{id:string;name:string}[]>([]);
  const [from,setFrom]=useState(new Date(Date.now()-90*86400000).toISOString().slice(0,10)),[to,setTo]=useState(todayIso()),[item,setItem]=useState(""),[branch,setBranch]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const root=`/companies/${companyId}/procurement/supplier-performance`;
  async function load(){if(!companyId)return;setBusy(true);setError("");try{const data=(await http.get<Report>(root,{params:{from,to,branchId:branch||undefined,itemId:item||undefined}})).data;setReport(data);setSettings(data.settings);}catch(e){setError(apiError(e,"Unable to load supplier performance."));}finally{setBusy(false);}}
  useEffect(()=>{if(companyId){void load();void Promise.all([inventoryItemsApi.list(companyId),http.get<{id:string;name:string}[]>(`/companies/${companyId}/branches`).catch(()=>({data:[] as {id:string;name:string}[]}))]).then(([i,b])=>{setItems(i);setBranches(asItems(b.data));}).catch(e=>setError(apiError(e,"Unable to load report filters.")));}},[companyId]);
  async function save(){if(!settings)return;setBusy(true);setError("");try{await http.post(`${root}/settings`,settings);await load();}catch(e){setError(apiError(e,"Unable to save score settings."));}finally{setBusy(false);}}
  const metric=(value:number|undefined,suffix="%")=>value==null?tx("Insufficient data"):`${qty(value)}${suffix}`;
  return <main className="prq-page"><PageHeader title={tx("Supplier performance")} subtitle={tx("Compare delivery, quality and fulfilment evidence. Supplier selection remains a purchasing decision.")}/>{error&&<p role="alert">{tx(error)}</p>}
    <section className="prq-panel"><div className="prq-form-grid"><label>{tx("From")}<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{tx("To")}<Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>{tx("Branch")}<Select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">{tx("All authorized branches")}</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select></label><label>{tx("Item and eligible alternatives")}<Select value={item} onChange={e=>setItem(e.target.value)}><option value="">{tx("All items")}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</Select></label></div><Button disabled={busy} onClick={()=>void load()}>{tx("Compare suppliers")}</Button></section>
    {report&&<><p>{tx(report.scope)} · {report.from} – {report.to}</p>{report.suppliers.map(s=><section className="prq-panel" key={s.id}><h2>{s.name}</h2><p>{tx(s.eligible?"Eligible for new orders":"Not eligible for new orders")} · {s.paymentTermDays} {tx("payment-term days")}</p><p>{tx(s.alternativeExplanation)}</p><dl><dt>{tx("On-time deliveries")}</dt><dd>{metric(s.onTimePercent)}</dd><dt>{tx("Average delivery lead time")}</dt><dd>{metric(s.averageLeadDays,` ${tx("days")}`)}</dd><dt>{tx("Average line fulfilment")}</dt><dd>{metric(s.averageLineFulfilmentPercent)}</dd><dt>{tx("Average line rejection rate")}</dt><dd>{metric(s.averageLineRejectionPercent)}</dd><dt>{tx("Average line return rate")}</dt><dd>{metric(s.averageLineReturnPercent)}</dd><dt>{tx("Overall score")}</dt><dd>{s.score==null?tx(s.scoreStatus):`${qty(s.score)} / 100`}</dd></dl><details><summary>{tx("Supplier price trends")}</summary><p>{tx(s.priceTrendNote)}</p>{s.excludedPriceRecords>0&&<p>{s.excludedPriceRecords} {tx("receipts excluded because comparable cost or saved conversion is missing")}</p>}{!s.priceTrends.length?<p>{tx("Insufficient comparable price history")}</p>:<div className="prq-table-wrap"><table className="prq-table"><thead><tr>{["Item","Month","Net base quantity","Weighted price per base unit","Receipts"].map(h=><th key={h}>{tx(h)}</th>)}</tr></thead><tbody>{s.priceTrends.map(p=><tr key={`${p.itemId}:${p.month}:${p.baseUnit}`}><td>{p.itemName}</td><td>{p.month}</td><td>{qty(p.baseQuantity)} {p.baseUnit}</td><td>{money(p.weightedUnitPrice)} / {p.baseUnit}</td><td>{p.receipts.map(r=><span key={r.grnId}><Link to={`/companies/${companyId}/grns/${r.grnId}`}>{r.grnNo}</Link> </span>)}</td></tr>)}</tbody></table></div>}</details><details><summary>{s.orders} {tx("orders")} · {s.deliveries} {tx("deliveries")}</summary><ul>{s.transactions.map(p=><li key={p.id}><Link to={`/companies/${companyId}/procurement/purchase-orders/${p.id}`}>{p.poNo}</Link> · {p.orderDate}<ul>{p.receipts.map(r=><li key={r.id}><Link to={`/companies/${companyId}/grns/${r.id}`}>{r.grnNo}</Link></li>)}{p.returns.map(r=><li key={r.id}><Link to={`/companies/${companyId}/procurement/purchase-returns/${r.id}`}>{r.returnNo}</Link></li>)}</ul></li>)}</ul></details></section>)}</>}
    {canManage&&settings&&<section className="prq-panel"><h2>{tx("Optional supplier scoring")}</h2><label><Checkbox checked={settings.enabled} onChange={e=>setSettings(s=>s&&({...s,enabled:e.target.checked}))}/>{tx("Enable overall scores when enough evidence is available")}</label><div className="prq-form-grid">{(["deliveryWeight","qualityWeight","fulfilmentWeight","minimumDeliveries"] as const).map((field,i)=><label key={field}>{tx(["Delivery weight","Quality weight","Fulfilment weight","Minimum deliveries"][i])}<Input type="number" min={field==="minimumDeliveries"?1:0} max={1000} value={settings[field]} onChange={e=>setSettings(s=>s&&({...s,[field]:Number(e.target.value)}))}/></label>)}</div><Button disabled={busy} onClick={()=>void save()}>{tx("Save scoring settings")}</Button></section>}
  </main>;
}
