import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {http} from "../../../api/http";
import {PageHeader} from "../../../components/PageHeader";
import {Button} from "../../../components/ui/button";
import {Select} from "../../../components/ui/select";
import {Textarea} from "../../../components/ui/textarea";
import {useI18n} from "../../../i18n";
import {useHasPermission} from "../../../auth/usePermissions";
import {suppliersApi,type SupplierLookup} from "../api/purchasingApi";
import RequisitionDocuments from "../components/RequisitionDocuments";
import {apiError,money,qty,useCompanyId} from "../components/p2pShared";
type Submission={id:string;kind:string;referenceId:string;status:string;version:string;supplierName:string;resultId?:string;reviewReason?:string;payload:{supplierReference:string;notes:string;deliveryDate?:string;invoiceDate?:string;validUntil?:string;paymentTermDays:number;lines:{lineId:string;quantity:number;unitPrice:number;taxRatePercent:number;discountPercent:number;freight:number}[]}};
type Accounts={accounts:{id:string;userId:string;supplierId:string;isActive:boolean}[];users:{id:string;name:string}[]};
export default function SupplierSubmissionsPage(){
 const {tx}=useI18n(),companyId=useCompanyId(),canManage=useHasPermission("purchasing.manage"),canReview=useHasPermission("purchasing.create");const [rows,setRows]=useState<Submission[]>([]),[accounts,setAccounts]=useState<Accounts|null>(null),[suppliers,setSuppliers]=useState<SupplierLookup[]>([]),[rfqs,setRfqs]=useState<{id:string;reference:string}[]>([]),[userId,setUser]=useState(""),[supplierId,setSupplier]=useState(""),[rfqId,setRfq]=useState(""),[reasons,setReasons]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState("");const root=`/companies/${companyId}/procurement`;
 async function load(){setRows((await http.get<Submission[]>(`${root}/supplier-submissions`)).data);}
 useEffect(()=>{if(!companyId)return;void load().catch(e=>setError(apiError(e,"Unable to load supplier submissions.")));if(canReview)void Promise.all([suppliersApi.lookup(companyId),http.get<{id:string;reference:string}[]>(`${root}/quotations`)]).then(([s,r])=>{setSuppliers(s);setRfqs(r.data);}).catch(e=>setError(apiError(e,"Unable to load supplier invitations.")));if(canManage)void http.get<Accounts>(`${root}/supplier-access`).then(r=>setAccounts(r.data)).catch(e=>setError(apiError(e,"Company-wide access is required to manage supplier accounts.")));},[companyId,canManage,canReview]);
 async function action(path:string,body:unknown){setBusy(true);setError("");try{await http.post(`${root}/${path}`,body);await load();if(accounts)setAccounts((await http.get<Accounts>(`${root}/supplier-access`)).data);}catch(e){setError(apiError(e,"Unable to save supplier portal changes."));}finally{setBusy(false);}}
 return <main className="prq-page"><PageHeader title={tx("Supplier submissions")} subtitle={tx("Validate supplier updates before they affect quotations, orders or invoices.")}/>{error&&<p role="alert">{tx(error)}</p>}{rows.map(s=><section className="prq-panel" key={s.id}><h2>{s.supplierName} · {s.payload.supplierReference} · {tx(s.kind)}</h2><p>{tx(s.status)} · <Link to={s.kind==="Quotation"?`/procurement/quotations/${s.referenceId}`:`/procurement/purchase-orders/${s.referenceId}`}>{tx("Open related purchasing document")}</Link></p><p>{s.payload.notes}</p><p>{s.payload.deliveryDate&&`${tx("Delivery")}: ${s.payload.deliveryDate} `}{s.payload.invoiceDate&&`${tx("Invoice date")}: ${s.payload.invoiceDate} `}{s.payload.validUntil&&`${tx("Valid until")}: ${s.payload.validUntil}`}</p><p>{tx("Payment-term days")}: {s.payload.paymentTermDays}</p>{s.payload.lines.map((l,i)=><p key={l.lineId}>{tx("Submitted line")} {i+1}: {qty(l.quantity)} × {money(l.unitPrice)} · {tx("Tax")}: {qty(l.taxRatePercent)}% · {tx("Discount")}: {qty(l.discountPercent)}% · {tx("Freight")}: {money(l.freight)}</p>)}<RequisitionDocuments companyId={companyId} id={s.id} documentType="supplier-submission" editable={false}/><p>{s.reviewReason}</p>{s.resultId&&s.kind==="Invoice"&&<Link to={`/procurement/supplier-invoices/${s.resultId}`}>{tx("Open invoice for matching and AP approval")}</Link>}{s.status==="Submitted"&&canReview&&<fieldset disabled={busy}><legend>{tx("Internal validation")}</legend><label>{tx("Decision reason")}<Textarea maxLength={1000} value={reasons[s.id]||""} onChange={e=>setReasons({...reasons,[s.id]:e.target.value})}/></label><Button disabled={!reasons[s.id]?.trim()} onClick={()=>void action(`supplier-submissions/${s.id}/decision`,{version:s.version,accept:true,reason:reasons[s.id]})}>{tx("Accept and apply validated details")}</Button><Button variant="outline" disabled={!reasons[s.id]?.trim()} onClick={()=>void action(`supplier-submissions/${s.id}/decision`,{version:s.version,accept:false,reason:reasons[s.id]})}>{tx("Reject submission")}</Button></fieldset>}</section>)}
 {canReview&&<section className="prq-panel"><h2>{tx("Invite a supplier to quote")}</h2><label>{tx("Supplier")}<Select value={supplierId} onChange={e=>setSupplier(e.target.value)}><option value="">{tx("Select supplier")}</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></label><label>{tx("Quotation request")}<Select value={rfqId} onChange={e=>setRfq(e.target.value)}><option value="">{tx("Select quotation request")}</option>{rfqs.map(r=><option key={r.id} value={r.id}>{r.reference}</option>)}</Select></label><Button disabled={busy||!supplierId||!rfqId} onClick={()=>void action("supplier-invitations",{supplierId,requestId:rfqId})}>{tx("Make request available in supplier workspace")}</Button></section>}
 {accounts&&<section className="prq-panel"><h2>{tx("Supplier account access")}</h2><p>{tx("Create a sign-in account through user administration, then link it to its supplier here. Supplier accounts need no internal purchasing permissions.")}</p><label>{tx("Sign-in account")}<Select value={userId} onChange={e=>setUser(e.target.value)}><option value="">{tx("Choose account")}</option>{accounts.users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</Select></label><label>{tx("Supplier")}<Select value={supplierId} onChange={e=>setSupplier(e.target.value)}><option value="">{tx("Select supplier")}</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></label><Button disabled={busy||!userId||!supplierId} onClick={()=>void action("supplier-access",{userId,supplierId,isActive:true})}>{tx("Enable supplier access")}</Button>{accounts.accounts.map(a=><p key={a.id}>{accounts.users.find(u=>u.id===a.userId)?.name} · {suppliers.find(s=>s.id===a.supplierId)?.name} · {tx(a.isActive?"Active":"Disabled")} <Button variant="outline" disabled={busy} onClick={()=>void action("supplier-access",{userId:a.userId,supplierId:a.supplierId,isActive:!a.isActive})}>{tx(a.isActive?"Disable access":"Enable access")}</Button></p>)}</section>}</main>;
}
