import {useEffect,useState} from "react";
import {http} from "../../../api/http";
import {PageHeader} from "../../../components/PageHeader";
import {Button} from "../../../components/ui/button";
import {Input} from "../../../components/ui/input";
import {Select} from "../../../components/ui/select";
import {Textarea} from "../../../components/ui/textarea";
import {useI18n} from "../../../i18n";
import RequisitionDocuments from "../components/RequisitionDocuments";
import {apiError,money,qty,todayIso,useCompanyId} from "../components/p2pShared";
type SourceLine={id:string;itemName:string;unit?:string;uomName?:string;quantity:number;unitPrice?:number;taxRatePercent?:number;specification?:string};
type Order={id:string;poNo:string;revision:number;status:string;currencyCode:string;expectedDeliveryDate?:string;terms?:string;lines:SourceLine[]};
type Request={id:string;reference:string;responseDue:string;currencyCode:string;lines:SourceLine[]};
type PortalLine={lineId:string;quantity:number;unitPrice:number;taxRatePercent:number;discountPercent:number;freight:number};
type Submission={id:string;kind:string;status:string;version:string;reviewReason?:string;payload:{supplierReference:string;notes:string}};
type Data={orders:Order[];requests:Request[];submissions:Submission[]};
export default function SupplierPortalPage(){
 const {tx}=useI18n(),companyId=useCompanyId();const [data,setData]=useState<Data>({orders:[],requests:[],submissions:[]}),[kind,setKind]=useState("Quotation"),[referenceId,setReference]=useState(""),[supplierReference,setSupplierReference]=useState(""),[deliveryDate,setDeliveryDate]=useState(todayIso()),[invoiceDate,setInvoiceDate]=useState(todayIso()),[validUntil,setValidUntil]=useState(todayIso(30)),[paymentTermDays,setTerms]=useState(30),[notes,setNotes]=useState(""),[lines,setLines]=useState<PortalLine[]>([]),[key,setKey]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const root=`/companies/${companyId}/procurement/supplier-portal`,source=kind==="Quotation"?data.requests.find(r=>r.id===referenceId):data.orders.find(o=>o.id===referenceId);
 async function load(){setData((await http.get<Data>(root)).data);}
 useEffect(()=>{if(!companyId)return;setData({orders:[],requests:[],submissions:[]});void load().catch(e=>setError(apiError(e,"Supplier access is unavailable. Ask the purchasing team to link your account to the approved supplier.")));},[companyId]);
 useEffect(()=>{const sourceLines=kind==="Quotation"?data.requests.find(r=>r.id===referenceId)?.lines:data.orders.find(o=>o.id===referenceId)?.lines;setLines((sourceLines??[]).map(l=>({lineId:l.id,quantity:l.quantity,unitPrice:l.unitPrice??0,taxRatePercent:l.taxRatePercent??0,discountPercent:0,freight:0})));},[kind,referenceId]);
 useEffect(()=>setKey(crypto.randomUUID()),[kind,referenceId,supplierReference,deliveryDate,invoiceDate,validUntil,paymentTermDays,notes,lines]);
 async function draft(){if(busy)return;setBusy(true);setError("");try{await http.post(`${root}/drafts`,{clientRequestId:key,kind,referenceId,supplierReference,deliveryDate:kind==="Quotation"||kind==="DeliveryUpdate"?deliveryDate:null,invoiceDate:kind==="Invoice"?invoiceDate:null,validUntil:kind==="Quotation"?validUntil:null,paymentTermDays,notes,lines:kind==="Quotation"||kind==="Invoice"?lines.filter(l=>l.quantity>0):[]});await load();setReference("");setSupplierReference("");setNotes("");}catch(e){setError(apiError(e,"Unable to save submission. Your entered details are retained."));}finally{setBusy(false);}}
 async function submit(row:Submission){setBusy(true);setError("");try{await http.post(`${root}/${row.id}/submit`,{version:row.version});await load();}catch(e){setError(apiError(e,"Unable to submit. Attach the required document and refresh before retrying."));}finally{setBusy(false);}}
 const patch=(index:number,value:Partial<PortalLine>)=>setLines(old=>old.map((l,i)=>i===index?{...l,...value}:l));
 return <main className="prq-page"><PageHeader title={tx("Supplier workspace")} subtitle={tx("Your quotations, issued orders, delivery updates and invoice submissions.")}/>{error&&<p role="alert">{tx(error)}</p>}<section className="prq-panel"><h2>{tx("Issued purchase orders")}</h2>{data.orders.map(o=><details key={o.id}><summary>{o.poNo} · {tx("Revision")} {o.revision} · {tx(o.status)}</summary><p>{o.currencyCode} · {tx("Expected delivery")}: {o.expectedDeliveryDate||"—"}</p><p>{o.terms}</p>{o.lines.map(l=><p key={l.id}>{l.itemName} · {qty(l.quantity)} {l.uomName} × {money(l.unitPrice??0)} · {tx("Tax")}: {qty(l.taxRatePercent??0)}%</p>)}</details>)}</section>
 <form className="prq-panel" onSubmit={e=>{e.preventDefault();void draft();}}><fieldset disabled={busy}><legend>{tx("Prepare a submission")}</legend><label>{tx("Submission type")}<Select value={kind} onChange={e=>{setKind(e.target.value);setReference("");}}>{["Quotation","Acknowledgement","DeliveryUpdate","Invoice"].map(k=><option key={k}>{tx(k)}</option>)}</Select></label><label>{tx(kind==="Quotation"?"Invited quotation request":"Your purchase order")}<Select required value={referenceId} onChange={e=>setReference(e.target.value)}><option value="">{tx("Choose reference")}</option>{kind==="Quotation"?data.requests.map(r=><option key={r.id} value={r.id}>{r.reference} · {tx("Due")}: {r.responseDue}</option>):data.orders.map(o=><option key={o.id} value={o.id}>{o.poNo}</option>)}</Select></label><label>{tx("Your document or acknowledgement reference")}<Input required maxLength={120} value={supplierReference} onChange={e=>setSupplierReference(e.target.value)}/></label>{(kind==="Quotation"||kind==="DeliveryUpdate")&&<label>{tx("Expected delivery date")}<Input required type="date" value={deliveryDate} onChange={e=>setDeliveryDate(e.target.value)}/></label>}{kind==="Invoice"&&<label>{tx("Invoice date")}<Input required type="date" max={todayIso()} value={invoiceDate} onChange={e=>setInvoiceDate(e.target.value)}/></label>}{kind==="Quotation"&&<><label>{tx("Quote valid until")}<Input required type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label><label>{tx("Payment terms in days")}<Input type="number" min={0} max={365} value={paymentTermDays} onChange={e=>setTerms(Number(e.target.value))}/></label></>}
 {(kind==="Quotation"||kind==="Invoice")&&<><p>{tx("Currency")}: {source?.currencyCode} · {tx("Set quantity to zero to omit a line.")}</p>{lines.map((l,i)=><fieldset key={l.lineId}><legend>{source?.lines.find(x=>x.id===l.lineId)?.itemName} · {source?.lines.find(x=>x.id===l.lineId)?.unit??source?.lines.find(x=>x.id===l.lineId)?.uomName}</legend>{(["quantity","unitPrice","taxRatePercent",...(kind==="Quotation"?["discountPercent","freight"]:[])] as (keyof Omit<PortalLine,"lineId">)[]).map((field)=><label key={field}>{tx(({quantity:"Quantity",unitPrice:"Unit price",taxRatePercent:"Tax percent",discountPercent:"Discount percent",freight:"Freight amount"})[field])}<Input type="number" min={0} step="0.0001" value={l[field]} onChange={e=>patch(i,{[field]:Number(e.target.value)})}/></label>)}</fieldset>)}</>}
 <label>{tx("Notes")}<Textarea maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><Button type="submit" disabled={!referenceId}>{tx("Save draft and add supporting documents")}</Button></fieldset></form>
 <section className="prq-panel"><h2>{tx("Submission history")}</h2><p>{tx("Submitted details require internal validation before they update purchasing or Accounts Payable. Corrections use a new submission.")}</p>{data.submissions.map(s=><details key={s.id} open={s.status==="Draft"}><summary>{s.payload.supplierReference} · {tx(s.kind)} · {tx(s.status)}</summary><p>{s.payload.notes}</p><p>{s.reviewReason}</p><RequisitionDocuments companyId={companyId} id={s.id} documentType="supplier-submission" editable={s.status==="Draft"} onChanged={()=>void load()}/>{s.status==="Draft"&&<Button disabled={busy} onClick={()=>void submit(s)}>{tx("Submit for internal validation")}</Button>}</details>)}</section></main>;
}
