import type {
  FnbReportColumnDto,
  FnbReportDto,
  FnbReportRow,
} from "../api/fnbReportsApi";
import { formatReportValue, visibleReportColumns } from "./fnbReportFormatting";

function csvEscape(value: unknown) {
  const text = String(value ?? "");
  return `"${text.replace(/"/g, '""')}"`;
}

export function exportRowsToCsv({
  filename,
  report,
  columns,
  rows,
}: {
  filename: string;
  report: FnbReportDto;
  columns: FnbReportColumnDto[];
  rows: FnbReportRow[];
}) {
  const visibleColumns = visibleReportColumns(columns);
  const contextRows = [
    ["Report", report.reportName],
    ["Company", report.companyName ?? ""],
    ["Branch", report.branchName ?? ""],
    ["Filter", report.filterSummary ?? ""],
    ["Currency", report.currencyCode ?? "ETB"],
    ["Costing", report.costingMethod ?? ""],
    ["Period status", report.periodStatus ?? ""],
    ["Generated at", report.generatedAtUtc ?? ""],
    ["Generated by", report.generatedBy ?? ""],
    [],
  ];

  const header = visibleColumns.map((column) => column.label);
  const body = rows.map((row) =>
    visibleColumns.map((column) =>
      formatReportValue(row[column.key], column.format, report.currencyCode),
    ),
  );

  const csv = [...contextRows, header, ...body]
    .map((line) => line.map(csvEscape).join(","))
    .join("\n");

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();

  URL.revokeObjectURL(url);
}
