import type {
  FnbReportColumnDto,
  FnbReportDto,
  FnbReportRow,
} from "../api/fnbReportsApi";
import { visibleReportColumns } from "./fnbReportFormatting";

function csvEscape(value: unknown) {
  // Spreadsheet applications evaluate formulas even in quoted CSV cells.
  const raw = String(value ?? "");
  const text = typeof value === "string" && (/^\s*[=+\-@]/.test(raw) || /^[\t\r\n]/.test(raw))
    ? `'${raw}`
    : raw;
  return `"${text.replace(/"/g, '""')}"`;
}

export function buildReportCsv({
  report,
  columns,
  rows,
  search = "",
}: {
  report: FnbReportDto;
  columns: FnbReportColumnDto[];
  rows: FnbReportRow[];
  search?: string;
}) {
  const visibleColumns = visibleReportColumns(columns);
  const contextRows = [
    ["Report", report.reportName],
    ["Company", report.companyName ?? ""],
    ["Branch", report.branchName ?? ""],
    ["Filter", report.filterSummary ?? ""],
    ["Currency", report.currencyCode ?? "ETB"],
    ["Costing", report.costingMethod ?? ""],
    ["Period status", report.periodStatus ?? ""],
    ["Generated at", report.generatedAtUtc ?? ""],
    ["Generated by", report.generatedBy ?? ""],
    ["Time zone", report.timeZone ?? ""],
    ["Methodology", report.methodology ?? ""],
    ["Search within result", search],
    ["Exported rows", rows.length],
    ["Full report rows", report.rows.length],
    ...report.warnings.map((warning) => ["Report warning", warning.message]),
    ...(report.reconciliation ? [
      ["Reconciliation basis", "Current stock balances compared with posted inventory ledger"],
      ["Stock balance value", report.reconciliation.inventoryValue],
      ["Ledger value", report.reconciliation.ledgerValue],
      ["Reconciliation difference", report.reconciliation.difference],
    ] : []),
    [],
  ];

  const header = visibleColumns.map((column) => column.label);
  const body = rows.map((row) =>
    visibleColumns.map((column) =>
      ["number", "currency", "percent"].includes(column.format)
        ? numericCsvValue(row[column.key])
        : row[column.key],
    ),
  );

  return "\uFEFF" + [...contextRows, header, ...body]
    .map((line) => line.map(csvEscape).join(","))
    .join("\r\n");
}

function numericCsvValue(value: unknown): number | string {
  if (value == null || value === "") return "";
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : "";
}

export function exportRowsToCsv({ filename, ...options }: Parameters<typeof buildReportCsv>[0] & { filename: string }) {
  const csv = buildReportCsv(options);

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();

  URL.revokeObjectURL(url);
}
