// src/features/inventory/siv/components/SivDraftEditorScreen.tsx

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { getApiError } from "../../../../api/getApiError";
import { useSivScreenController } from "../hooks/useSivScreenController";
import { sivApi } from "../api/sivApi";
import { sivDetailsPath } from "../utils/sivWorkflowRoutes";
import { useErpNavigate } from "../../../../routes/useErpNavigation";
import { useI18n } from "../../../../i18n";
import type {
  FifoIssueCandidateDto,
  InventoryItemSearchResult,
  LocationOption,
  SivDetailsDto,
} from "../api/sivApi";
import "../pages/siv-draft.css";

type ScreenMode = "create" | "edit";

type Props = {
  companyId: string;
  branchId: string;
  departmentId?: string | null;
  currentLocationId?: string | null;
  requestedByUserId?: string | null;
  mode?: ScreenMode;
  draftId?: string | null;
  initialDraft?: SivDetailsDto | null;
};


type PickedItem = {
  itemId: string;
  itemName: string;
  uomId: string;
  uomCode: string;
};

const EMPTY_ITEM: PickedItem = {
  itemId: "",
  itemName: "",
  uomId: "",
  uomCode: "",
};

const QTY_FORMATTER = new Intl.NumberFormat(undefined, {
  maximumFractionDigits: 3,
});

function formatQty(value: number | string | null | undefined): string {
  if (value == null || value === "") return "-";

  const numericValue = Number(value);
  return Number.isFinite(numericValue) ? QTY_FORMATTER.format(numericValue) : "-";
}

function toDateInputValue(value?: string | null): string {
  if (!value) return "";

  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "" : date.toISOString().slice(0, 10);
}

function isGuidLike(value?: string | null): boolean {
  if (!value) return false;
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
    value.trim(),
  );
}

function readableText(value: unknown): string {
  return value == null ? "" : String(value).trim();
}

function getFifoDisplayDate(option: Partial<FifoIssueCandidateDto>): string {
  return toDateInputValue(option.expiryDate ?? null);
}

function getFifoSourceLabel(option: FifoIssueCandidateDto): string {
  const sourceNumber = readableText(option.sourceNumber);

  // Do not show backend GUIDs as FIFO/GRN names. They are technical IDs, not user-facing labels.
  if (sourceNumber && !isGuidLike(sourceNumber)) return sourceNumber;

  return "GRN receipt";
}

function formatFifoOptionLabel(option: FifoIssueCandidateDto): string {
  const grnNumber = getFifoSourceLabel(option);
  const displayDate = getFifoDisplayDate(option);
  return `${grnNumber} - ${displayDate || "No expiry"}`;
}

function isPastDate(value?: string | null): boolean {
  if (!value) return false;

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return false;

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  return date < today;
}

type FifoOptionWithUiKey = FifoIssueCandidateDto & {
  /** Frontend-only unique key generated by useSivScreenController. */
  __fifoOptionKey?: string;
};

function getFifoOptionKey(option: Partial<FifoIssueCandidateDto>): string {
  const uiKey = (option as FifoOptionWithUiKey).__fifoOptionKey;
  if (uiKey) return uiKey;

  return [
    option.fifoLayerId || "no-layer",
    option.sourceId || "no-source",
    option.sourceNumber || "no-number",
    option.itemId || "no-item",
    option.uomId || "no-uom",
    option.receivedDate || "no-received",
    option.batchNo || "no-batch",
    option.expiryDate || "no-expiry",
    option.availableQty ?? "no-qty",
    option.availableBaseQty ?? "no-base-qty",
  ].join("|");
}


function getItemUomId(item: InventoryItemSearchResult): string {
  return item.uomId || item.baseUomId || "";
}

function getItemUomCode(item: InventoryItemSearchResult): string {
  return item.uomCode || item.baseUomCode || "";
}

function formatItemName(item: InventoryItemSearchResult): string {
  const englishName = String(item.name ?? "").trim() || "Unnamed item";
  const amharicName = String(item.localName ?? "").trim();
  return amharicName && amharicName !== englishName && !englishName.includes(amharicName)
    ? `${englishName} - ${amharicName}`
    : englishName;
}

function toPickedItem(item?: InventoryItemSearchResult): PickedItem {
  if (!item) return EMPTY_ITEM;

  return {
    itemId: item.id,
    itemName: formatItemName(item),
    uomId: getItemUomId(item),
    uomCode: getItemUomCode(item),
  };
}

function normalizeQuantityInput(rawValue: string): number | "" {
  if (rawValue === "") return "";

  const numericValue = Number(rawValue);
  if (!Number.isFinite(numericValue)) return "";

  return Math.max(0, numericValue);
}

function getSavedSivId(value: unknown): string {
  const candidates: unknown[] = [];

  if (typeof value === "string") {
    candidates.push(value);
  } else if (value && typeof value === "object") {
    const record = value as Record<string, unknown>;

    candidates.push(
      record.id,
      record.Id,
      record.sivId,
      record.SivId,
      record.documentId,
      record.DocumentId,
      record.value,
      record.Value,
    );

    for (const key of ["data", "result", "siv", "document"]) {
      const nested = record[key];

      if (nested && typeof nested === "object") {
        const nestedRecord = nested as Record<string, unknown>;

        candidates.push(
          nestedRecord.id,
          nestedRecord.Id,
          nestedRecord.sivId,
          nestedRecord.SivId,
          nestedRecord.documentId,
          nestedRecord.DocumentId,
          nestedRecord.value,
          nestedRecord.Value,
        );
      }
    }
  }

  for (const candidate of candidates) {
    if (typeof candidate !== "string") continue;

    const normalized = candidate.trim();

    if (isGuidLike(normalized)) {
      return normalized;
    }
  }

  return "";
}

export default function SivDraftEditorScreen({
  companyId,
  branchId,
  departmentId,
  currentLocationId,
  requestedByUserId,
  mode = "create",
  draftId,
  initialDraft = null,
}: Props) {
  const navigate = useErpNavigate();
  const { tx } = useI18n();

  // Keep this as a variable instead of an inline object so the controller can
  // accept `requestedByUserId` without causing excess-property issues if older
  // hook typings have not been updated yet.
  const controllerParams = {
    companyId,
    branchId,
    departmentId: departmentId ?? undefined,
    currentLocationId: currentLocationId ?? undefined,
    requestedByUserId: requestedByUserId ?? undefined,
  };

  const ctrl = useSivScreenController(controllerParams);

  const {
    loading,
    saving,
    error,
    success,

    fromLocations: sourceLocations,
    toLocations: destinationLocations,
    selectedFromLocationId: selectedSourceLocationId,
    selectedToLocationId,
    setSelectedFromLocationId,
    setSelectedToLocationId,

    issueDate,
    setIssueDate,
    notes,
    setNotes,

    lines,
    selectedLines,
    addLine,
    removeLine,
    updateLine,
    hydrateDraft,
    onPickItem,
    onChangeFifo,
    searchInventoryItems,
    canSaveDraft,
    createDraft,
    updateDraft,
  } = ctrl;

  const [itemOptions, setItemOptions] = useState<InventoryItemSearchResult[]>([]);
  const [itemsLoading, setItemsLoading] = useState(false);
  const [clientError, setClientError] = useState("");
  const [editHydrated, setEditHydrated] = useState(false);
  const [loadingDraft, setLoadingDraft] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const submitLockRef = useRef(false);

  const isEdit = mode === "edit" && Boolean(draftId);
  const isCreate = !isEdit;
  const isDisabledUntilHydrated = isEdit && !editHydrated;
  const isBusy = loading || saving || loadingDraft || submitting;

  const selectedDestination = useMemo(
    () => destinationLocations.find((location) => location.id === selectedToLocationId),
    [destinationLocations, selectedToLocationId],
  );

  const mustPickDestination = destinationLocations.length > 1;

  const requestingLocationName =
    selectedDestination?.name ??
    (currentLocationId ? tx("Current location") : tx("Your branch location"));

  const duplicateLineKeys = useMemo(() => {
    const counts = new Map<string, number>();

    for (const line of lines) {
      if (!line.itemId) continue;

      const key = `${line.itemId}|${line.uomId || "no-uom"}|${line.batchNo || "no-batch"}`;
      counts.set(key, (counts.get(key) ?? 0) + 1);
    }

    const duplicates = new Set<string>();

    for (const line of lines) {
      if (!line.itemId) continue;

      const key = `${line.itemId}|${line.uomId || "no-uom"}|${line.batchNo || "no-batch"}`;
      if ((counts.get(key) ?? 0) > 1) duplicates.add(line.key);
    }

    return duplicates;
  }, [lines]);

  const totalQty = useMemo(
    () => lines.reduce((sum, line) => sum + Number(line.qty || 0), 0),
    [lines],
  );

  const hasOverStock = useMemo(
    () =>
      lines.some((line) => {
        const availableQty = line.availableQty ?? line.availableBaseQty;
        const requestedQty = Number(line.qty || 0);

        return requestedQty > 0 && availableQty != null && requestedQty > availableQty;
      }),
    [lines],
  );

  const hasDuplicateLines = duplicateLineKeys.size > 0;
  const canSave =
    canSaveDraft &&
    !isBusy &&
    !isDisabledUntilHydrated &&
    !hasOverStock &&
    !hasDuplicateLines;

  const canSubmit =
    canSave &&
    isEdit &&
    Boolean(draftId) &&
    isGuidLike(draftId);

  const saveButtonText = saving
    ? tx("Saving...")
    : isEdit
      ? tx("Save changes")
      : tx("Save draft");

  const clearClientError = useCallback(() => setClientError(""), []);

  useEffect(() => {
    if (isCreate) {
      setEditHydrated(false);
      setLoadingDraft(false);
    }
  }, [isCreate]);

  useEffect(() => {
    setItemOptions([]);
  }, [selectedSourceLocationId]);

  useEffect(() => {
    clearClientError();
  }, [
    clearClientError,
    issueDate,
    notes,
    selectedSourceLocationId,
    selectedToLocationId,
    lines.length,
  ]);

  useEffect(() => {
    if (!isEdit || editHydrated) return;

    let isMounted = true;

    async function hydrateExistingDraft() {
      if (initialDraft) {
        hydrateDraft(initialDraft);
        setEditHydrated(true);
        return;
      }

      if (!draftId) return;

      setLoadingDraft(true);

      try {
        const draft = await sivApi.getById(companyId, draftId);

        if (!isMounted) return;

        if (!draft) {
          setClientError(tx("Draft not found."));
          return;
        }

        hydrateDraft(draft);
        setEditHydrated(true);
      } catch (err) {
        if (isMounted) {
          setClientError(getApiError(err, tx("Failed to load SIV draft.")));
        }
      } finally {
        if (isMounted) setLoadingDraft(false);
      }
    }

    void hydrateExistingDraft();

    return () => {
      isMounted = false;
    };
  }, [companyId, draftId, editHydrated, hydrateDraft, initialDraft, isEdit]);

  const loadItemOptions = useCallback(async () => {
    if (!selectedSourceLocationId || itemOptions.length > 0 || itemsLoading) return;

    setItemsLoading(true);

    try {
      const items = await searchInventoryItems("");
      setItemOptions(Array.isArray(items) ? items.filter((item) => item.isActive !== false) : []);
    } catch (err) {
      setItemOptions([]);
      setClientError(getApiError(err, tx("Failed to load inventory items.")));
    } finally {
      setItemsLoading(false);
    }
  }, [itemOptions.length, itemsLoading, searchInventoryItems, selectedSourceLocationId]);

  const handleSave = useCallback(async () => {
    clearClientError();

    if (hasDuplicateLines) {
      setClientError(tx("Duplicate item + batch + UOM combinations are not allowed."));
      return;
    }

    if (hasOverStock) {
      setClientError(tx("One or more requested quantities exceed available source stock."));
      return;
    }

    if (!canSave) return;

    try {
      const saved =
        isEdit && draftId ? await updateDraft(draftId) : await createDraft();

      if (!saved) {
        return;
      }

      const savedId =
        getSavedSivId(saved) ||
        (isEdit && isGuidLike(draftId) ? draftId! : "");

      if (!savedId) {
        throw new Error(
          tx("The draft was saved, but the API did not return a valid SIV ID."),
        );
      }

      navigate(sivDetailsPath(companyId, savedId), {
        replace: true,
      });
    } catch (err) {
      setClientError(getApiError(err, tx("Failed to save SIV draft.")));
    }
  }, [
    branchId,
    canSave,
    clearClientError,
    companyId,
    createDraft,
    draftId,
    hasDuplicateLines,
    hasOverStock,
    isEdit,
    navigate,
    updateDraft,
  ]);

  const handleSubmit = useCallback(async () => {
    if (submitLockRef.current) return;

    clearClientError();

    if (hasDuplicateLines) {
      setClientError(tx("Duplicate item + batch + UOM combinations are not allowed."));
      return;
    }

    if (hasOverStock) {
      setClientError(tx("One or more requested quantities exceed available source stock."));
      return;
    }

    if (!canSubmit) return;

    // Submission is a workflow transition for an already persisted draft.
    // It must never create or update the draft implicitly.
    if (!isEdit || !draftId || !isGuidLike(draftId)) {
      setClientError(tx("Save the draft before submitting it for approval."));
      return;
    }

    submitLockRef.current = true;
    setSubmitting(true);

    try {
      await sivApi.submit(companyId, branchId, draftId, {
        rowVersion: initialDraft?.rowVersion ?? null,
        remarks: notes.trim() || null,
      });

      navigate(sivDetailsPath(companyId, draftId), {
        replace: true,
      });
    } catch (err) {
      setClientError(getApiError(err, tx("Failed to submit SIV for approval.")));
    } finally {
      submitLockRef.current = false;
      setSubmitting(false);
    }
  }, [
    branchId,
    canSubmit,
    clearClientError,
    companyId,
    draftId,
    hasDuplicateLines,
    hasOverStock,
    initialDraft?.rowVersion,
    isEdit,
    navigate,
    notes,
  ]);

  const handleAddLine = useCallback(() => {
    clearClientError();
    addLine();
    void loadItemOptions();
  }, [addLine, clearClientError, loadItemOptions]);

  const handleSourceChange = useCallback(
    (value: string) => {
      clearClientError();
      setSelectedFromLocationId(value);
      setItemOptions([]);
    },
    [clearClientError, setSelectedFromLocationId],
  );

  const handleDestinationChange = useCallback(
    (value: string) => {
      clearClientError();
      setSelectedToLocationId(value);
    },
    [clearClientError, setSelectedToLocationId],
  );

  if (loading) {
    return (
      <div className="page">
        <div
          style={{
            padding: 48,
            textAlign: "center",
            color: "var(--text-muted)",
            fontSize: 13,
          }}
        >
          {tx("Loading...")}
        </div>
      </div>
    );
  }

  const displayError = clientError || error;

  return (
    <div className="page siv-page">
      <div className="page-header">
        <div>
          <div className="page-kicker">{tx("Inventory")} - {tx("SIV")} - {isEdit ? tx("Edit") : tx("New")}</div>
          <div className="page-title">
            {isEdit ? tx("Edit Stock Issue Request") : tx("New Stock Issue Request")}
          </div>
          <div className="page-sub">
            {isEdit
              ? tx("Update lines or header details, then save.")
              : mustPickDestination
                ? tx("Select the source, destination, and requested items.")
                : tx("Add the items you need. Choose Warehouse, Production, or Pastry as the source.")}
          </div>
        </div>

        <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
          {hasOverStock && (
            <div className="badge badge-danger" style={{ fontSize: 11 }}>{tx("Warning: Qty exceeds source stock")}</div>
          )}

          {hasDuplicateLines && (
            <div className="badge badge-danger" style={{ fontSize: 11 }}>{tx("Warning: Duplicate lines")}</div>
          )}

          <button className="btn" onClick={handleSave} disabled={!canSave}>
            {saveButtonText}
          </button>

          <button
            className="btn btn-primary"
            onClick={handleSubmit}
            disabled={!canSubmit}
            title={isCreate ? tx("Save the draft before submitting it for approval.") : undefined}
          >
            {submitting ? tx("Submitting...") : tx("Submit for Approval")}
          </button>

          <button className="btn" onClick={() => navigate(-1)} disabled={saving}>
            {tx("Cancel")}
          </button>
        </div>
      </div>

      {displayError && (
        <div className="alert alert-danger" style={{ marginBottom: 14 }}>
          {displayError}
        </div>
      )}

      {success && (
        <div className="alert alert-success" style={{ marginBottom: 14 }}>
          {success}
        </div>
      )}

      <div className="card" style={{ marginBottom: 14 }}>
        <div className="card-header">
          <div className="card-title">{tx("Requisition Details")}</div>
          <div className="card-subtitle">
            {tx("You are requesting stock as:")} <strong>{requestingLocationName}</strong>
          </div>
        </div>

        <div
          className="card-body"
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr 1fr",
            gap: 16,
          }}
        >
          <div className="field" style={{ marginBottom: 0 }}>
            <label className="field-label">
              {tx("Issue from")}
              <span style={{ color: "var(--danger)", marginLeft: 3 }}>*</span>
            </label>

            <select
              className="select"
              value={selectedSourceLocationId}
              disabled={isDisabledUntilHydrated || loading}
              onChange={(event) => handleSourceChange(event.target.value)}
            >
              <option value="">{loading ? tx("Loading source locations...") : tx("-- Select source location --")}</option>
              {sourceLocations.map((location: LocationOption) => (
                <option key={location.id} value={location.id}>
                  {location.name}
                  {location.code ? ` (${location.code})` : ""}
                </option>
              ))}
            </select>

            <div style={{ marginTop: 5, fontSize: 11, color: "var(--text-muted)" }}>
              {tx("Choose the stock source: Warehouse, Production, or Pastry.")}
            </div>
          </div>

          <div className="field" style={{ marginBottom: 0 }}>
            <label className="field-label">
              {tx("Deliver to Location")}
              <span style={{ color: "var(--danger)", marginLeft: 3 }}>*</span>
            </label>

            {mustPickDestination ? (
              <select
                className="select"
                value={selectedToLocationId}
                disabled={isDisabledUntilHydrated || loading}
                onChange={(event) => handleDestinationChange(event.target.value)}
              >
                <option value="">{loading ? tx("Loading destinations...") : tx("-- Select destination --")}</option>

                {destinationLocations.map((location: LocationOption) => (
                  <option key={location.id} value={location.id}>
                    {location.name}
                    {location.code ? ` (${location.code})` : ""}
                  </option>
                ))}
              </select>
            ) : (
              <div
                style={{
                  padding: "8px 11px",
                  background: "var(--surface-2)",
                  border: "1px solid var(--border-soft)",
                  borderRadius: "var(--r)",
                  fontSize: 13,
                  color: "var(--text-muted)",
                  minHeight: 36,
                  display: "flex",
                  alignItems: "center",
                  gap: 8,
                }}
              >
                <span
                  style={{
                    width: 7,
                    height: 7,
                    borderRadius: "50%",
                    background: selectedToLocationId ? "var(--success)" : "var(--danger)",
                    flexShrink: 0,
                  }}
                />
                {requestingLocationName}
              </div>
            )}

            <div style={{ marginTop: 5, fontSize: 11, color: "var(--text-muted)" }}>
              {mustPickDestination
                ? tx("Choose the consuming location receiving this issue.")
                : selectedToLocationId
                  ? tx("Auto-assigned because only one destination location is available.")
                  : tx("No destination location is assigned to your user. Ask an admin to assign a consumption location.")}
            </div>
          </div>

          <div className="field" style={{ marginBottom: 0 }}>
            <label className="field-label">{tx("Required by Date")}</label>
            <input
              className="input"
              type="date"
              value={issueDate}
              disabled={isDisabledUntilHydrated}
              onChange={(event) => {
                clearClientError();
                setIssueDate(event.target.value);
              }}
            />
          </div>

          <div className="field" style={{ gridColumn: "1 / -1", marginBottom: 0 }}>
            <label className="field-label">{tx("Purpose / Remarks")}</label>
            <textarea
              className="input siv-textarea"
              value={notes}
              disabled={isDisabledUntilHydrated}
              onChange={(event) => {
                clearClientError();
                setNotes(event.target.value);
              }}
              placeholder={tx("Describe the purpose of this requisition.")}
              rows={2}
            />
          </div>
        </div>
      </div>

      <div className="card" style={{ padding: 0 }}>
        <div className="card-header">
          <div>
            <div className="card-title">{tx("Requested Items")}</div>
            <div className="card-subtitle">
              {selectedLines.length > 0
                ? `${selectedLines.length} ${tx(selectedLines.length === 1 ? "item" : "items")} - ${tx("Total qty")}: ${formatQty(totalQty)}`
                : tx("Add the items you need from the selected source location.")}
            </div>
          </div>

          <button
            className="btn btn-sm"
            onClick={handleAddLine}
            disabled={isDisabledUntilHydrated || !selectedSourceLocationId || !selectedToLocationId}
            title={
              !selectedSourceLocationId
                ? tx("Select a source location first")
                : !selectedToLocationId
                  ? tx("Select a destination first")
                  : tx("Add a line")
            }
          >
            {tx("+ Add item")}
          </button>
        </div>

        {(!selectedSourceLocationId || !selectedToLocationId) && (
          <div
            style={{
              padding: "14px 16px",
              background: "var(--surface-2)",
              borderBottom: "1px solid var(--border-soft)",
              fontSize: 13,
              color: "var(--text-muted)",
            }}
          >{tx("Info: Source and destination locations are required before adding items.")}</div>
        )}

        <div style={{ overflowX: "auto" }}>
          <table className="table">
            <thead>
              <tr>
                <th style={{ width: 40 }}>#</th>
                <th style={{ width: 300 }}>{tx("Item")}</th>
                <th style={{ width: 240 }}>{tx("FIFO Lot")}</th>
                <th style={{ width: 80 }}>{tx("UOM")}</th>
                <th style={{ width: 110, textAlign: "right" }}>{tx("Available")}</th>
                <th style={{ width: 110, textAlign: "right" }}>{tx("Request Qty")}</th>
                <th style={{ width: 120 }}>{tx("Batch")}</th>
                <th style={{ width: 110 }}>{tx("Expiry")}</th>
                <th>{tx("Notes")}</th>
                <th style={{ width: 52 }} />
              </tr>
            </thead>

            <tbody>
              {!selectedSourceLocationId || !selectedToLocationId ? (
                <tr>
                  <td
                    colSpan={10}
                    style={{
                      padding: 48,
                      textAlign: "center",
                      color: "var(--text-soft)",
                      fontSize: 13,
                    }}
                  >
                    {tx("Source and destination locations are required before adding items.")}
                  </td>
                </tr>
              ) : (
                lines.map((line, index) => {
                  const availableQty = line.availableQty ?? line.availableBaseQty;
                  const requestedQty = Number(line.qty || 0);
                  const isDuplicate = duplicateLineKeys.has(line.key);
                  const isOverStock =
                    requestedQty > 0 && availableQty != null && requestedQty > availableQty;
                  const expired = isPastDate(line.expiryDate);

                  const lineError =
                    line.lineError ||
                    (isDuplicate ? tx("Duplicate item + batch + UOM on this request.") : "") ||
                    (isOverStock ? `${tx("Exceeds available stock")} (${formatQty(availableQty)}).` : "");

                  return (
                    <tr
                      key={line.key}
                      style={{
                        verticalAlign: "top",
                        background: lineError
                          ? "var(--danger-bg)"
                          : expired
                            ? "var(--warn-bg)"
                            : undefined,
                      }}
                    >
                      <td
                        style={{
                          padding: "10px 10px",
                          fontFamily: "var(--mono)",
                          fontSize: 11,
                          color: "var(--text-muted)",
                          paddingTop: 14,
                        }}
                      >
                        {String(index + 1).padStart(2, "0")}
                      </td>

                      <td style={{ padding: "8px 10px" }}>
                        <select
                          className="select"
                          style={{ fontSize: 12 }}
                          value={line.itemId}
                          disabled={!selectedSourceLocationId || isDisabledUntilHydrated || itemsLoading}
                          onFocus={() => void loadItemOptions()}
                          onChange={(event) => {
                            clearClientError();
                            const item = itemOptions.find((option) => option.id === event.target.value);
                            void onPickItem(line.key, toPickedItem(item));
                          }}
                        >
                          <option value="">{itemsLoading ? tx("Loading items...") : tx("-- Select item --")}</option>

                          {line.itemId &&
                            !itemOptions.some((item) => item.id === line.itemId) && (
                              <option key={`saved-item-${line.key}-${line.itemId}`} value={line.itemId}>
                                {line.itemName || tx("Saved item")}
                                {line.uomCode ? ` - ${line.uomCode}` : ""}
                              </option>
                            )}

                          {itemOptions.map((item) => {
                            const uomCode = getItemUomCode(item);
                            const itemName = formatItemName(item);

                            return (
                              <option key={item.id} value={item.id}>
                                {itemName}
                                {item.sku ? ` - ${item.sku}` : ""}
                                {uomCode ? ` - ${uomCode}` : ""}
                              </option>
                            );
                          })}
                        </select>

                        {line.itemName && (
                          <div
                            style={{
                              fontSize: 10,
                              color: "var(--text-muted)",
                              marginTop: 3,
                              fontFamily: "var(--mono)",
                            }}
                          >
                            {line.itemName}
                          </div>
                        )}
                      </td>

                      <td style={{ padding: "8px 10px" }}>
                        {line.loadingFifo ? (
                          <div style={{ fontSize: 12, color: "var(--text-muted)", padding: "8px 0" }}>
                            {tx("Loading...")}
                          </div>
                        ) : line.fifoOptions.length > 0 ? (
                          <select
                            className="select"
                            style={{ fontSize: 12, minWidth: 200 }}
                            value={line.selectedFifoKey}
                            disabled={isDisabledUntilHydrated}
                            onChange={(event) => {
                              clearClientError();
                              onChangeFifo(line.key, event.target.value);
                            }}
                          >
                            <option value="">{tx("-- Select lot --")}</option>

                            {line.fifoOptions.map((option) => {
                              const fifoOptionKey = getFifoOptionKey(option);

                              return (
                                <option key={fifoOptionKey} value={fifoOptionKey}>
                                  {formatFifoOptionLabel(option)}
                                </option>
                              );
                            })}
                          </select>
                        ) : line.itemId ? (
                          <div style={{ fontSize: 12, color: "var(--danger)", padding: "8px 0" }}>
                            {tx("No stock available at this source location.")}
                          </div>
                        ) : (
                          <div style={{ fontSize: 12, color: "var(--text-soft)", padding: "8px 0" }}>-</div>
                        )}
                      </td>

                      <td style={{ padding: "8px 10px" }}>
                        <input
                          className="input"
                          style={{ fontSize: 12, color: "var(--text-muted)" }}
                          value={line.uomCode || "-"}
                          readOnly
                          disabled
                        />
                      </td>

                      <td style={{ padding: "8px 10px", textAlign: "right" }}>
                        <input
                          className="input"
                          style={{
                            fontSize: 12,
                            textAlign: "right",
                            fontFamily: "var(--mono)",
                            color:
                              availableQty != null && availableQty === 0
                                ? "var(--danger)"
                                : "var(--text-muted)",
                          }}
                          value={line.loadingAvailability ? "-" : formatQty(availableQty)}
                          readOnly
                          disabled
                        />
                      </td>

                      <td style={{ padding: "8px 10px" }}>
                        <input
                          className="input"
                          type="number"
                          min="0"
                          step="0.001"
                          style={{
                            fontSize: 12,
                            textAlign: "right",
                            fontFamily: "var(--mono)",
                            borderColor: isOverStock ? "var(--danger)" : undefined,
                          }}
                          value={line.qty}
                          disabled={isDisabledUntilHydrated}
                          onChange={(event) => {
                            clearClientError();
                            updateLine(line.key, "qty", normalizeQuantityInput(event.target.value));
                          }}
                          placeholder="0.000"
                        />
                      </td>

                      <td style={{ padding: "8px 10px" }}>
                        <input
                          className="input"
                          style={{ fontSize: 12, color: "var(--text-muted)" }}
                          value={line.batchNo || "-"}
                          readOnly
                          disabled
                        />
                      </td>

                      <td style={{ padding: "8px 10px" }}>
                        <input
                          className="input"
                          style={{
                            fontSize: 12,
                            color: expired ? "var(--danger)" : "var(--text-muted)",
                            borderColor: expired ? "var(--danger)" : undefined,
                          }}
                          value={toDateInputValue(line.expiryDate) || tx("No expiry")}
                          readOnly
                          disabled
                          title={expired ? tx("This lot has expired") : undefined}
                        />
                      </td>

                      <td style={{ padding: "8px 10px" }}>
                        <textarea
                          className="input"
                          style={{ minHeight: 60, fontSize: 12, resize: "vertical" }}
                          value={line.remarks}
                          placeholder={tx("Optional")}
                          disabled={isDisabledUntilHydrated}
                          onChange={(event) => {
                            clearClientError();
                            updateLine(line.key, "remarks", event.target.value);
                          }}
                        />

                        {lineError && (
                          <div style={{ marginTop: 5, color: "var(--danger)", fontSize: 11 }}>{tx("Warning:")} {lineError}</div>
                        )}

                        {expired && !lineError && (
                          <div style={{ fontSize: 11, color: "var(--warn)", marginTop: 3 }}>{tx("Warning: Selected lot has expired.")}</div>
                        )}
                      </td>

                      <td style={{ padding: "8px 10px", textAlign: "center" }}>
                        <button
                          className="btn btn-sm"
                          style={{
                            padding: "4px 8px",
                            color: "var(--danger)",
                            borderColor: "var(--danger-border)",
                          }}
                          onClick={() => {
                            clearClientError();
                            removeLine(line.key);
                          }}
                          disabled={lines.length === 1 || isDisabledUntilHydrated}
                          title={tx("Remove this line")}
                        >
                          {tx("Remove")}
                        </button>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>

            {selectedLines.length > 0 && (
              <tfoot>
                <tr style={{ background: "var(--surface-2)", fontWeight: 600 }}>
                  <td
                    colSpan={5}
                    style={{
                      padding: "8px 10px",
                      fontSize: 11,
                      textTransform: "uppercase",
                      letterSpacing: "0.06em",
                      color: "var(--text-muted)",
                    }}
                  >
                    {tx("Total requested")}
                  </td>

                  <td
                    style={{
                      padding: "8px 10px",
                      textAlign: "right",
                      fontFamily: "var(--mono)",
                      fontSize: 14,
                    }}
                  >
                    {formatQty(totalQty)}
                  </td>

                  <td colSpan={4} />
                </tr>
              </tfoot>
            )}
          </table>
        </div>

        <div
          style={{
            padding: "9px 16px",
            fontSize: 11,
            color: "var(--text-soft)",
            borderTop: "1px solid var(--border-soft)",
            background: "var(--surface-2)",
            display: "flex",
            alignItems: "center",
            gap: 16,
            flexWrap: "wrap",
          }}
        >
          <span>{tx("Info: Requested qty cannot exceed available source stock.")}</span>
          <span>{tx("Duplicate item + batch + UOM combinations are blocked.")}</span>
          <span>{tx("Batch and expiry are assigned from the selected FIFO lot.")}</span>
        </div>
      </div>

      <div className="siv-bottom-actions">
        <button className="btn" onClick={() => navigate(-1)} disabled={saving}>
          {tx("Cancel")}
        </button>

        <button className="btn" onClick={handleSave} disabled={!canSave}>
          {saveButtonText}
        </button>

        <button
          className="btn btn-primary"
          onClick={handleSubmit}
          disabled={!canSubmit}
          title={isCreate ? tx("Save the draft before submitting it for approval.") : undefined}
        >
          {submitting ? tx("Submitting...") : tx("Submit for Approval")}
        </button>
      </div>
    </div>
  );
}

