import { useI18n } from "../../../../i18n";
import type { FnbReportDto } from "../api/fnbReportsApi";
import { formatReportDateTime, formatReportMoney } from "../utils/fnbReportFormatting";

type Props = {
  report: FnbReportDto | null;
  methodology?: string | null;
  periodLabel: string;
};

function ContextPills({ items }: { items: Array<[string, string]> }) {
  return (
    <div className="fnb-report-context">
      {items.map(([label, value]) => (
        <div className="fnb-context-pill" key={label}>
          <span>{label}</span>
          <strong>{value}</strong>
        </div>
      ))}
    </div>
  );
}

/**
 * Everything a reader needs to trust a report: printable heading, calculation
 * basis, applied scope, server warnings, and the inventory reconciliation.
 */
export function FnbReportContext({ report, methodology, periodLabel }: Props) {
  const { tx } = useI18n();

  return (
    <>
      {report ? (
        <section className="fnb-print-header" aria-label={tx("Printable report header")}>
          <div>
            <p>{tx("F&B Control Report")}</p>
            <h2>{report.reportName}</h2>
          </div>
          <div>
            <strong>{report.companyName || tx("Company")}</strong>
            <span>{report.branchName || tx("Branch")}</span>
          </div>
        </section>
      ) : null}

      {methodology ? (
        <section className="fnb-methodology" aria-label={tx("Report methodology")}>
          <strong>{tx("Report basis")}</strong>
          <p>{methodology}</p>
        </section>
      ) : null}

      {report ? (
        <section aria-label={tx("Report context")}>
          <ContextPills
            items={[
              [tx("Period"), periodLabel],
              [tx("Status"), tx(report.periodStatus || "Open")],
              [tx("Costing"), report.costingMethod || tx("Configured")],
              [tx("Currency"), report.currencyCode || "-"],
              [tx("Generated"), formatReportDateTime(report.generatedAtUtc, report.timeZone)],
              [tx("Time zone"), report.timeZone || "-"],
              [tx("Generated by"), report.generatedBy || "-"],
              [tx("Scope"), report.filterSummary || "-"],
            ]}
          />
        </section>
      ) : null}

      {report?.warnings?.length ? (
        <section className="fnb-warning-list" aria-label={tx("Report warnings")}>
          {report.warnings.map((warning) => (
            <div key={`${warning.code}-${warning.message}`} className={`fnb-warning fnb-warning--${warning.severity || "warning"}`}>
              <strong>{tx(warning.severity === "info" ? "Note" : "Warning")}</strong>
              <span>{warning.message}</span>
            </div>
          ))}
        </section>
      ) : null}

      {report?.reconciliation ? (
        <section className="fnb-methodology" aria-label={tx("Inventory reconciliation")}>
          <strong>
            {tx("Inventory reconciliation")}:{" "}
            {report.reconciliation.isReconciled ? tx("Reconciled") : tx("Difference requires review")}
          </strong>
          <p>{tx("Current stock balances compared with the posted inventory ledger at report generation.")}</p>
          <ContextPills
            items={[
              [tx("Stock balance value"), formatReportMoney(report.reconciliation.inventoryValue, report.currencyCode)],
              [tx("Ledger value"), formatReportMoney(report.reconciliation.ledgerValue, report.currencyCode)],
              [tx("Difference"), formatReportMoney(report.reconciliation.difference, report.currencyCode)],
            ]}
          />
        </section>
      ) : null}
    </>
  );
}
