import { FormEvent, memo, useMemo, useState } from "react";

import type { TelegramMiniAppAuthResult } from "./telegramMiniApp.types";
import { notifyTelegram } from "./telegramWebApp";

type Props = {
  auth: TelegramMiniAppAuthResult;
  onLink: (token: string) => Promise<void>;
};

function TelegramEmployeeLinkPage({ auth, onLink }: Props) {
  const [linkToken, setLinkToken] = useState("");
  const [consentAccepted, setConsentAccepted] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const displayName = useMemo(() => {
    return (
      auth.telegramDisplayName ??
      auth.telegramUserName ??
      (auth.telegramUserId ? `Telegram ${auth.telegramUserId}` : "Telegram user")
    );
  }, [auth.telegramDisplayName, auth.telegramUserId, auth.telegramUserName]);

  async function handleSubmit(event: FormEvent) {
    event.preventDefault();

    const token = linkToken.trim().toUpperCase();

    if (!token) {
      setError("Enter the employee link code generated by HR.");
      return;
    }

    if (!consentAccepted) {
      setError("You must accept consent before linking your employee profile.");
      return;
    }

    setSubmitting(true);
    setError(null);

    try {
      await onLink(token);
      notifyTelegram("success");
    } catch (err) {
      notifyTelegram("error");
      setError(
        err instanceof Error
          ? err.message
          : "Unable to link Telegram account.",
      );
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <section className="tg-link-card">
      <div className="tg-link-card__icon"></div>

      <h2>Link Employee Account</h2>

      <p>
        Your Telegram account is authenticated. Enter the link code generated
        from your employee profile to connect this Telegram account to Hotel Nova
        ERP.
      </p>

      <div className="tg-link-identity">
        <span>Telegram account</span>
        <strong>{displayName}</strong>
      </div>

      <form onSubmit={handleSubmit} className="tg-link-form">
        <label>
          <span>HR link code</span>
          <input
            value={linkToken}
            onChange={(e) => {
              setLinkToken(e.target.value.toUpperCase());
              if (error) setError(null);
            }}
            placeholder="Example: A7HF-82KQ"
            autoCapitalize="characters"
            autoCorrect="off"
            spellCheck={false}
            disabled={submitting}
          />
        </label>

        <label className="tg-link-consent">
          <input
            type="checkbox"
            checked={consentAccepted}
            onChange={(e) => setConsentAccepted(e.target.checked)}
            disabled={submitting}
          />

          <span>
            I consent to link my Telegram account to my Hotel Nova employee
            profile for attendance, store requests, approvals, and ERP
            notifications.
          </span>
        </label>

        {error ? <div className="tg-link-error">{error}</div> : null}

        <button type="submit" disabled={submitting}>
          {submitting ? "Linking..." : "Link Employee"}
        </button>
      </form>

      <small>
        Ask HR or your manager to generate a fresh Telegram link code from your
        employee profile. Link codes are short-lived and can be used only once.
      </small>
    </section>
  );
}

export default memo(TelegramEmployeeLinkPage);
